### ISSUE TITLE
ImportError: cannot import name 'AsyncResult' from 'telegram.utils'

### ISSUE THREAD

**Issue by williamflow** [alexander-akhmetov/python-telegram#10]
```
Traceback (most recent call last):
  File "Client.py", line 1, in <module>
    from telegram.client import Telegram
  File "/usr/local/lib/python3.7/dist-packages/telegram/client.py", line 12, in <module>
    from telegram.utils import AsyncResult
ImportError: cannot import name 'AsyncResult' from 'telegram.utils' (/usr/local/lib/python3.7/dist-packages/telegram/utils/__init__.py)
```

**Comment by alexander-akhmetov** [comment]
Hi! Which `python-telegram` version do you use? 

Also, it looks like you use another package, not `python-telegram`:

```/usr/local/lib/python3.7/dist-packages/telegram/utils/__init__.py```

`dist-packages/telegram/utils/__init__.py` does not look like a file from this package. Do you have some system package installed which contains this file?
