### ISSUE TITLE
addChatMembers responese "None"

### ISSUE THREAD

**Issue by ioogle** [alexander-akhmetov/python-telegram#100]
Thanks for your great work.

I want to call the api "addChatMembers" to add users to my channel. But it shows "None" after the calling. I've search many places but still no solution, could you help me? Thanks a lot. 

I added some codes to the `client.py` file:

```python
def add_chat_members(self, chat_id: int, user_ids: List[int]) -> AsyncResult:
    data = {
        '@type': 'addChatMembers',
        'user_ids': user_ids,
     }
    return self._send_data(data)
```

and also here is the main file:

```
result = tg.add_chat_members(-10088888868, user_ids[:20])
result.wait()
print(result.update)
```

the result is `None`.

**Comment by alexander-akhmetov** [comment]
Hi! 

It shows `None` and doesn't add members to the chat? AsyncResult instance has also `ok_received`, `error` and `error_info` [attributes](https://github.com/alexander-akhmetov/python-telegram/blob/master/telegram/utils.py#L52), can you try to print them?

Also, you can try to enable verbose logging if you want tdlib to print all messages:

```
tg = Telegram(..., tdlib_verbosity=7)
```

**Comment by ioogle** [comment]
Thanks for your kind replay. The advices helped greatly. I've got the error messages and solved them:

```
error_info {'@type': 'error', 'code': 403, 'message': 'USER_PRIVACY_RESTRICTED', '@extra': {'request_id': 'xxx'}}
error_info {'@type': 'error', 'code': 3, 'message': 'User not found', '@extra': {'request_id': 'xxx'}}
```

Thanks again for your great work!
