### ISSUE TITLE
Method "send_message" just save message in local db

### ISSUE THREAD

**Issue by lBrane** [alexander-akhmetov/python-telegram#103]
Script example:
--------------------------------------------------
from telegram.client import Telegram
tg = Telegram(
        api_id=ID,
        api_hash='HASH',
        phone='PHONE',
        database_encryption_key='KEY',
    )

tg.login()
result = tg.get_chats()
result.wait()

CHAT_ID = <chat_id>

result = tg.send_message(
    chat_id=CHAT_ID,
    text='Test Message'
)

result.wait()

print(result.update)

------------------------------------------------------

**Actual result:** In the update, I received the message data, but the status of the message is "messageSendingStatePending"
**Expected result:** Message should be sent to chat

**Additional info:**
If after wait(), add a little sleep (2-3 seconds), then the message is sent to the chat, otherwise it is just stored in the local database.

**Comment by alexander-akhmetov** [comment]
I'm closing this issue, please reopen if you have problems.
