### ISSUE TITLE
method "sendMessageAlbum" and "deleteMessages" not working

### ISSUE THREAD

**Issue by mahanxdev** [alexander-akhmetov/python-telegram#114]
Hi @alexander-akhmetov 
I used this for test **sendMessaageAlbum**, and as the tdlib document that **'input_message_content':** content should be in a vector so i put it in an array but is got error and not working
```
data = {
            'chat_id': chat_id,
            'reply_to_message_id': message_id,
            'input_message_content': [{
                '@type': 'inputMessagePhoto' ,
                type: {
                    '@type': 'inputFileRemote',
                    'id': file_id,
                },
                'caption': {
                    '@type': 'formattedText',
                    'text': text,
                },
            }, ],
        }
```
other hand is about **deleteMessages**. for message ids again i pushed message ids in an array( **message_ids = [5656552,4464646]** ) but not worked again
```
data = {
        'chat_id': chat_id,
        'message_ids': message_ids,
        'revoke': revoke,
    }
```
what should i do for them??

**Comment by alexander-akhmetov** [comment]
Hi,

Try to get the async result and print the error message if it is present. Also, you can increase verbosity of the library to get more debug information:

```python
tg = Telegram(
    ...
    tdlib_verbosity=7,
)

result = tg.delete_messages(chat_id=chat_id, message_ids= message_ids)
result.wait(raise_exc=True)

print(result.error_info)
```

You can also check out [this example](https://github.com/alexander-akhmetov/python-telegram/blob/master/examples/clear_group_messages.py), it uses the `delete_message` method.

**Comment by alexander-akhmetov** [comment]
I'm closing this issue, please reopen if you have problems.
