### ISSUE TITLE
How to deal with AsyncResult?

### ISSUE THREAD

**Issue by VladislavSahadji** [alexander-akhmetov/python-telegram#115]
I was testing the different methods of TDlib and most of them gave me AsyncResult<id> instead of str. Then I found the class parse_update, but I did not manage to use it in my code. Can you give me example how to deal with AsyncResult?

**Comment by mwxgaf** [comment]
Hi
work like this:
```python
t = Telegram(api_id=...)

t.login()

result = t.call_method('method_name',params={...})
result.wait()
print(result.update) # will give you the result in string
```

**Comment by VladislavSahadji** [comment]
Thank you, in fact I was confused by Object type usage. I thought I must use call_method also with this type, but it turned much easier finally.
