### ISSUE TITLE
How to work with object_ptr ?

### ISSUE THREAD

**Issue by mwxgaf** [alexander-akhmetov/python-telegram#117]
Hi @alexander-akhmetov 
Thank you because of your perfect library it is very clear,useful and easy
 Just I have a problem with calling methods which require data in `object_ptr` (written in `tdlib` documentation)
Exactly I mean `addContact` method. how should I give data in `params` ?
I act like this:
```python
result = t.call_method('addContact',params={'contact' : { 'phone_number' : 'some number' , 'first_name' : 'some name' , 'last_name' : 'some thing' , 'vcard' : '' , 'user_id' : 0 } , 'share_phone_number' : False})
result.wait()
print(result.update)
```
It prints `None` and does not add the contact.
Where is the problem? please help me :cry: 
This links may be useful:
[TDLib addContact Class Reference](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1add_contact.html)
[TDLib contact Class Reference](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1contact.html)
Excuse me if my English lang skill is weak I am not native.

**Comment by VladislavSahadji** [comment]
First of all try to print result.error_info for additional information.

**Comment by mwxgaf** [comment]
> First of all try to print result.error_info for additional information.

@VladislavSahadji thank you very much
`result.error_info` is this:

```python
{'@type': 'error', 'code': 3, 'message': 'User not found', '@extra': {'request_id': ...
```
I tried to set the `phone_number` to an empty string and set user id to an ID and then it worked!
But I want to add contacts by phone number not user id.
At the end I want an application which you give it a phone number and it returns you the telegram username if the phone number has telegram and also a username.how can I do this?

any way, thank you very much for your help so far.

**Comment by mwxgaf** [comment]
I found the solution
I should use `importContacts` method

**Comment by luvejo** [comment]
Yep, that's the way:
```python
tg.call_method('importContacts', {
    'contacts':[
        {'phone_number': '+57 555 555 5555', 'first_name': 'Holden'},
    ]
})
```
Thanks, @mwxgaf!
