### ISSUE TITLE
[QUESTION] how to change database_encryption_key?

### ISSUE THREAD

**Issue by LeonardoRick** [alexander-akhmetov/python-telegram#121]
Hi, this project is helping me a lot!
I just have this question about database_encryption and how can I change it. Just is case I forget or miss digit it in some point, how can I reset this value?

**Comment by alexander-akhmetov** [comment]
Hi, you can change it with [setDatabaseEncryptionKey](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1set_database_encryption_key.html), but i think you must know the old key. You can always remove the old database manually and start from scratch (you can specify it with [files_directory](https://github.com/alexander-akhmetov/python-telegram/blob/master/telegram/client.py#L36))

**Comment by LeonardoRick** [comment]
Thanks for answering @alexander-akhmetov! Can you give just a little light with a simple example that removes this old database?

**Comment by alexander-akhmetov** [comment]
I would do it manually, you need to remove `/tmp/.tdlib_files`, or you can specify a new path when you create a `Telegram` instance:

```
tg = Telegram(files_directory='<path>')
```
