### ISSUE TITLE
Not receveing messages from all chats

### ISSUE THREAD

**Issue by LeonardoRick** [alexander-akhmetov/python-telegram#125]
```
def tlgMsgHandler(update):
    # only text messages
    message_content = update['message']['content'].get('text', {})
    msg = message_content.get('text', '')
    chat_id = str(update['message']['chat_id'])
    print(f'chat Id: : {chat_id}\nmessage: {msg}')

constants = tlg_constants.TelegramConstants()

tlg: Telegram = Telegram(
    api_id=constants.api_id,
    api_hash=constants.api_hash,
    phone=constants.phone,
    database_encryption_key=constants.api_hash
)

tlg.login()  # connect to Telegram
tlg.add_message_handler(tlgMsgHandler)

tlg.idle()
```
Am I doing something wrong? I receive messages just from some channels but others don't.

I even tried to add 
```
result = tlg.get_chats()
result.wait()
```

before `tlg.add_message_handler(tlgMsgHandler)`, but I don't know if it's the case to use that

**Comment by alexander-akhmetov** [comment]
> I even tried to add
>
> result = tlg.get_chats()
> result.wait()

When you get all chats, you have to pass `offset_order`, see #58 and https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html .

If it still happens after you loaded all chats, you can try to enable debug logs (`tdlib_verbosity` to `5` or higher) to see what's happening. `tdlib` should print log messages every time it gets a new update from Telegram.

**Comment by LeonardoRick** [comment]
I tried `result = tlg.get_chats(offset_order=2 ** 63 - 1, offset_chat_id=0)` and `tretult = lg.get_chats(offset_order=9223372036854775807)`  followed by result.wait(), but it still not receving all messages. I tried debug it with `tdlib_verbosity` to `5` I it doesn't show neither `updateChatLastMessage` or `updateNewMessage` objects when I'm receiveing a message from a group that my code is not recognizing. Some other info are logged when this chats send messages So everytime this

**Comment by melkor217** [comment]
> I tried result = tlg.get_chats(offset_order=2 ** 63 - 1, offset_chat_id=0) and retult = lg.get_chats(offset_order=9223372036854775807) followed by result.wait(), but it still not receving all messages. I tried @melkor217 sollution too and no success too.

I'm not sure if you really have to get chats to make make your stuff work.

If so, check if `get_chats` returns chats you need.

If number of chats is somewhat round like 100, you probably want to load more.

> Something valid to metion is that I have around 35 channels

Not really, but keep in mind that "chat" entity could be a direct message, bot chat, group, channel etc.

**Comment by LeonardoRick** [comment]
@melkor217, Thanks a lot for answering. I think some things seems obvious to you but maybe I'm missing some gaps of understanding here. 

> I'm not sure if you really have to get chats to make make your stuff work.

If I don't need to get, how am I supposed to make it works normaly? Because some chats shows messages normaly. Others don't.


> If so, check if get_chats returns chats you need

I used:
```
result = tlg.get_chats(offset_order=2 ** 63 - 1, offset_chat_id=0)
print(result.wait())
```
Is that it? It's printing `None`, so probably I'm doing something wrong. Should I do something with this return? I'm just waiting it with `.wait()`.


> If number of chats is somewhat round like 100, you probably want to load more.

The return of get_chats should show that? If not, where can I find this info.

Again, thanks for answering and clarifying a lot of things.

**Comment by alexander-akhmetov** [comment]
> Is that it? It's printing None, so probably I'm doing something wrong. Should I do something with this return? I'm just waiting it with .wait().

I think there is a typo in your code, `.wait()` returns None. You need to call `wait()` to wait until Telegram returns the response, and then print the result:

```
result = tlg.get_chats(offset_order=2 ** 63 - 1, offset_chat_id=0)
result.wait()
print(result.update)
```


> If number of chats is somewhat round like 100, you probably want to load more.
The return of get_chats should show that? If not, where can I find this info.

`get_chats` returns you a response in this format:

```
{"@extra": {"request_id": "..."},
 "@type": "chats",
 "chat_ids": [1, 2, 3, 4]}
```
You can specify `limit` when you call `get_chats`, but in [tdlib's documentation](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html) they say `For optimal performance the number of returned chats is chosen by the library.` [This issue](https://github.com/tdlib/td/issues/56) also might be useful.

When you need to load all chats, you have to call `get_chat` until there is no more chats to load (response.update['chat_ids'] is empty). `get_chat` accepts `offset_order` and `offset_chat_id`, both are necessary to get the full list. Each chat has its own `order` and `id`. You start with `offset_order=2 ** 63 - 1` and `offset_chat_id=0`, and after you receive the first result, you get the latest chat_id, call `get_chat` and use this information to calculate next (offset_order, offset_chat_id) pair.

Something like that should get all chat ids:

```python
    ...
    tg.login()

    offset_chat_id = 0
    chat_ids = []
    offset_order = 2 ** 63 - 1
    chats_received = True

    while True:
        result = tg.get_chats(offset_order=offset_order, offset_chat_id=offset_chat_id)
        result.wait()

        if result.update['chat_ids']:
            chat_ids += result.update['chat_ids']
            chat_info = tg.get_chat(chat_ids[-1])
            chat_info.wait()
            offset_chat_id = chat_info.update['id']
            offset_order = chat_info.update['order']
        else:  # no more chats to load
            chats_received = False

    print('Chats: ', chat_ids)
```

**Comment by alexander-akhmetov** [comment]
But I'm not sure that you have to retrieve all chats to receive messages, to be honest. Is there anything specific about those chats, is it always the same chats or they are different from time to time?

**Comment by LeonardoRick** [comment]
Nice. I tried this implementation (you should just change `while True` to `while chats_received` for the future) and it returns a list of 222 items, so I guess the list is working. How am I supposed to use this list on my `message_handler()`? For now, it's just a list of IDs, so I'm not acctualy using it, right? Just getting them didn't solved the problem

> But I'm not sure that you have to retrieve all chats to receive messages, to be honest. Is there anything specific about those chats, is it always the same chats or they are different from time to time?

No it's just regular chats, I can't think of something special about them. Should I concern about muted chats? Because some of them are muted but I couldn't find a pattern with that, so it's just an observation

**Comment by alexander-akhmetov** [comment]
> Nice. I tried this implementation (you should just change while True to while chats_received for the future) and it returns a list of 222 items, so I guess the list is working. How am I supposed to use this list on my message_handler()? For now, it's just a list of IDs, so I'm not acctualy using it, right? Just getting them didn't solved the problem

No, I think not having chats locally should not affect receiving new messages. And it didn't work for you, so it doesn't.

> No it's just regular chats, I can't think of something special about them. Should I concern about muted chats? Because some of them are muted but I couldn't find a pattern with that, so it's just an observation

Then I think it's better to ask in [tdlib repository](https://github.com/tdlib/td/issues), sorry. You don't see these new messages even in tdlib logs, maybe they need to be processed in some specific way, something is misconfigured or they are special somehow.

**Comment by LeonardoRick** [comment]
What's weird is that it's not just some cases. The majority number of chat's is not sending me this `updateNewMessage`. What is even stranger is that it's not consistent. Some chat's not showing updates used to show sometimes. I now that because I writed down it's chat_id's and now they are not sending updates over `add_message_handler`. Is there a way that it can be blocked by the chat owner? Or maybe some privace setting I'm settled...

Anyway, thank's for helping and I will keep trying to find a way to fix this. I'm surprised that I can't find anyone that had this issue before. I'll keep looking for it too

**Comment by LeonardoRick** [comment]
Just for the record, I tried a basic `pyrogram` quick start and it's working ok for me. That's sad because I was really confotable using this library and probably i'll need to make a couple changes om my code. But If any ideia comes to my mind on how to fix it, I'll certainly let you guys know about that.
