### ISSUE TITLE
Login details and the API usage with repl.it

### ISSUE THREAD

**Issue by and7ey** [alexander-akhmetov/python-telegram#129]
Many thanks for your API.

My code looks like below - 
```
@app.route('/') # flask
def main():
  r = tg.call_method(...)

if __name__ == "__main__":
  tg = Telegram(...)
  tg.login()
  
  tg.add_message_handler(handler)

  r = tg.get_chats()
  r.wait()

  serve(app, host="0.0.0.0", port=8080)

  tg.idle()
  tg.stop()
```

Quite often this code requires me to login again (login = input auth code).

I use it with repl.it - it doesn't keep files after the restart.
I don't know why login is required so often - is it because of `files_directory` used, which is not saved after repl.it restart? (I don't send / receive any messages within my code). Is there any workaround? 

Can I keep login details (`tg`?) in the repl.it database?

**Comment by alexander-akhmetov** [comment]
Hi, python-telegram uses [tdlib](https://github.com/tdlib/td) internally and tdlib uses filesystem to keep its database. If there is no data, it has to login again. You can specify path to the files directory in python-telegram: `Telegram(files_directory='...')` and if there is a way to create a virtual persistent filesystem in repl.it, it could work. But I don't know if it's possible, sorry.
