### ISSUE TITLE
Weird errors in log

### ISSUE THREAD

**Issue by luksireiku** [alexander-akhmetov/python-telegram#131]
Errors like this keep appearing in the log, I don't think it is from my own code.

`{'@type': 'formattedText', 'text': '', 'entities': []}`

**Comment by alexander-akhmetov** [comment]
Hi, they are from tdlib, you can control it with `tdlib_verbosity` parameter (0-1024):

```python
tg = Telegram(..., tdlib_verbosity=<int>)
```
