### ISSUE TITLE
Using add_update_handler

### ISSUE THREAD

**Issue by Galicarnax** [alexander-akhmetov/python-telegram#137]
In the `telegram.client.Telegram`'s method `add_update_handler`, what are the names of avaliable handler types? It accepts just any name, without errors, but the assigned handler function is never called. Unfortunately, this method is not mentioned in examples. Say, I want to handle updates concerning the number of unread messages. If I use the name 'updateUnreadMessageCount' (from Telegram [docs](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1_update.html)), it does not work:
```python
t = Telegram(...)
t.login()

def handler():
    print('test')

t.add_update_handler('updateUnreadMessageCount', handler)
t.idle()
```
The example from tutorial which uses `add_message_handler` works fine.

**Comment by Gira-X** [comment]
It works with:

```python
def handler(result):
    pprint.pprint(result)
```

`result` is a dict and the above code will print:

```
{'@type': 'updateUnreadMessageCount',
 'chat_list': {'@type': 'chatListMain'},
 'unread_count': 1,
 'unread_unmuted_count': 1}
```

**Comment by Galicarnax** [comment]
Does not seem to work for me. After entering `t.idle()`, if I get new messages, or if I read unread messages in the regular Telegram Desktop client, nothing happens in the python code.

**Comment by alexander-akhmetov** [comment]
Hi, do you see any errors in the logs? Can you try to enable debug logs for tdlib?

```python
t = Telegram(..., tdlib_verbosity=7)
```

Then tdlib should print more information and all updates which it receives, as far as I know. 

Also, @Gira-X is right, your handler should accept one argument. If with debug logs you see this update in the output and your handler still isn't being called, something is wrong on the python side.

**Comment by Galicarnax** [comment]
Yes, with `tdlib_verbosity=7` I see outputs every second like "being to wait for updates" and "end to wait for updates", and if the unread count changes, I do see the event in the logs. So what can cause the handler to be ignored? I tried the version with one argument, does not help.

**Comment by alexander-akhmetov** [comment]
I tried to do the same and it works, but I had to load all chats before it started working. The [documentation](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_unread_message_count.html) says that it works only when the message database is used, I guess if a chat is not known for tdlib, is discards messages (but then they also shouldn't appear in the logs). 

```python
import argparse

from telegram.client import Telegram


def run_telegram(api_id, api_hash, phone):
    tg = Telegram(
        api_id=api_id,
        api_hash=api_hash,
        phone=phone,
        database_encryption_key='changeme1234',
    )
    tg.login()

    def handler_unread_count(update):
        print('>>> unread_message_count %s' % update)

    def handler_new_message(update):
        print('>>> new_message: %s' % update)

    tg.add_update_handler('updateUnreadMessageCount', handler_unread_count)
    tg.add_update_handler('updateNewMessage', handler_new_message)

    _load_all_chats(tg)

    tg.idle()


def _load_all_chats(tg):
    offset_chat_id = 0
    offset_order = 2 ** 63 - 1
    chats_received = True

    while chats_received:
        result = tg.get_chats(offset_order=offset_order, offset_chat_id=offset_chat_id)
        result.wait()

        if result.update['chat_ids']:
            chat_info = tg.get_chat(result.update['chat_ids'][-1])
            chat_info.wait()
            offset_chat_id = chat_info.update['id']
            offset_order = chat_info.update['order']
        else:  # no more chats to load
            chats_received = False


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('api_id', help='API id') 
    parser.add_argument('api_hash', help='API hash')
    parser.add_argument('phone', help='Phone')
    args = parser.parse_args()

    run_telegram(args.api_id, args.api_hash, args.phone)
```

**Comment by Galicarnax** [comment]
This works. Many thanks!

**Comment by Galicarnax** [comment]
@alexander-akhmetov , since some time ago the script you provided above does not work (probably after update), it says `KeyError: 'order'` for the line
```
offset_order = chat_info.update['order']
```
I am not sure why those offsets in your script are needed (not acquainted with the internals), but I tried to use a condition like
```
if 'order' in chat_info.update:
  offset_order = chat_info.update['order']
```
The script then runs, but it does not seem to catch the events when unread message count changes. Could you please give a hint on how can I modify the script above to restore the functionality of catching unread messages count events?

**Comment by alexander-akhmetov** [comment]
@Galicarnax 
Hm, I checked the script, and I still get `order` key in the update dictionary, so it works for me. `chat_info.update` object is a `tdlib` response, and I assumed that the order must always be there. Try to inspect the `chat_info.update ` object which doesn't have the key, maybe something is different about it?

---

> I am not sure why those offsets in your script are needed (not acquainted with the internals), but I tried to use a condition like


I used [this page](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html) to write the script and the page says:

> Chats are sorted by the pair (chat.position.order, chat.id) in descending order. (For example, to get a list of chats from the beginning, the offset_order should be equal to a biggest signed 64-bit number 9223372036854775807 == 2^63 - 1). For optimal performance the number of returned chats is chosen by the library.```

This doc also might be useful: https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats

**Comment by Galicarnax** [comment]
Here is the list of keys from the `chat_info.update` dictionary, no `order` there:
```
@type
id
type
title
photo
permissions
last_message
positions
is_marked_as_unread
is_blocked
has_scheduled_messages
can_be_deleted_only_for_self
can_be_deleted_for_all_users
can_be_reported
default_disable_notification
unread_count
last_read_inbox_message_id
last_read_outbox_message_id
unread_mention_count
notification_settings
reply_markup_message_id
client_data
@extra
```
Could the response structure have been changed is recent tdlib update?
PS. If that matters, the chat for which this error occurs is actually a group (though, again, it was there previously, and everything worked fine).

**Comment by alexander-akhmetov** [comment]
I was able to reproduce the issue with python-telegram `0.14.0` (tdlib `1.7.0`). The problem is related to the fact that one chat can now be in many different lists (folders/archive/main list): https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats. And I found the change in tdlib 1.7.0 changelog:

> Replaced the fields chat_list, order, is_sponsored and is_pinned in the class chat with the field positions, containing a list of the chat positions in various chat list.

So instead of the `order` field, now it's a list of positions: `chat_info.update['positions']` is a list of orders in chat lists. I think, in your case you need to find a position with `position['list']['@type'] == 'chatListMain'` and use it as the order. Here is an example of the `positions` list:

```python
[
    {
        '@type': 'chatPosition', 
        'list': {'@type': 'chatListMain'}, 
        'order': '12345', 
        'is_pinned': False
    }
]
```


You can also downgrade, the old script should work with tdlib 1.6.0. If you are using the precompiled tdlib from `python-telegram`, you can install a previous version of the library. Versions `0.11.0`-`0.13.0` use `1.6.0` ([changelog](https://python-telegram.readthedocs.io/en/latest/changelog.html)).

**Comment by Galicarnax** [comment]
Ok, so I have placed this:
```
for pos in chat_info.update['positions']:
  if pos['list']['@type'] == 'chatListMain':
    offset_order = pos['order']
    break
```
instead of just 
```
offset_order = chat_info.update['order']
```
and it seems to work now. Many thanks for your help, @alexander-akhmetov !
