### ISSUE TITLE
New Release date

### ISSUE THREAD

**Issue by Khrol** [alexander-akhmetov/python-telegram#139]
Current 0.12.0 release doesn't support reading messages form anonymous admins.
Any plans to release a new version to pypi with the latest build from https://github.com/tdlib/td#building?

**Comment by alexander-akhmetov** [comment]
Hi, `0.12.0` uses tdlib `v1.6.0` which is the latest official tag as I see. 

You can build tdlib from `master` and use it with python-telegram:

```python
tg = Telegram(
    library_path='path/to/libtdjson.so'
    ...
)
```
