### ISSUE TITLE
Send back the message read

### ISSUE THREAD

**Issue by majidnow** [alexander-akhmetov/python-telegram#146]
Hi
How can I tell to server a message received and read by user?

**Comment by alexander-akhmetov** [comment]
Hi. I think you need the method [viewMessages](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1view_messages.html). You probably need to open the chat before ([openChat](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1open_chat.html), [closeChat](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1close_chat.html)) or use `force_read` parameter of `viewMessages` instead.

You can use `Telergam.call_method` to call these. I'd also suggest to increase verbosity for development:

```python
tg = Telegram(..., tdlib_verbosity=7)

...

tg.call_method('viewMessages', {'chat_id': chat_id, 'force_read': False, ...})

```
