### ISSUE TITLE
Attempts to connect to IPv6

### ISSUE THREAD

**Issue by xrisk** [alexander-akhmetov/python-telegram#147]
I'm trying the basic echo code, and I'm facing this error:

```
[ 2][t 4][1610668100.594388008][ConnectionCreator.cpp:896][#1][!ConnectionCreator]	[[2001:b28:f23f:f005::a]:443] to DcId{5}: [PosixError : No route to host : 65 : Failed to connect to [[2001:b28:f23f:f005::a]:443]]
```

How can I tell the library to connect to an IPV4 address? (I don't have IPv6 connectivity). This problem is not present in the `tg_cli` binary built by tdlib.

**Comment by alexander-akhmetov** [comment]
Hi, can you try to set `prefer_ipv6` to False?

```
    tg = Telegram(...)

    tg.call_method(
        'setOption',
        {
            'name': 'prefer_ipv6',
            'value': {'@type': 'optionValueBoolean', 'value': False},
        },
    )

    tg.login()
```

**Comment by alexander-akhmetov** [comment]
According to [this issue](https://github.com/tdlib/td/issues/291) it is not an error but a warning.
