### ISSUE TITLE
32-bit version of libs

### ISSUE THREAD

**Issue by prawlins** [alexander-akhmetov/python-telegram#16]
I am trying to use python-telegram on  a Raspberry Pi which has a 32-bit core.  I loaded python-telegram using the command:

    `python3 -m pip install python-telegram`

When I run the tutorial I get this error:

    `lib/python3.6/site-packages/telegram/lib/linux/libtdjson.so: wrong ELF class: ELFCLASS64`

How do I get a 32-bit version of the libs?

**Comment by alexander-akhmetov** [comment]
Hi!

You need to compile [tdlib manually](https://github.com/tdlib/td) and then pass the path to the library as a parameter:

```python
tg = Telegram(
    ...
   library_path='path/to/libtdjson.so'
   ... 
)
```

**Comment by alexander-akhmetov** [comment]
I'm closing this issue, for now, if you have any questions, please reopen it :)
