### ISSUE TITLE
multiprocessing.Process 

### ISSUE THREAD

**Issue by dwap** [alexander-akhmetov/python-telegram#160]
tdlib страдает жуткой утечкой памяти, об этом хорошо известно. Например, похожий проект был прекращён: https://github.com/andrew-ld/python-tdlib
Я столкнулся с данной проблемой и обошел её создавая клиента как multiprocessing.Process со взаимодействием через Pipe, Queue, Event, Value, etc. Отслеживаю потребление памяти и пересоздаю Process, не прибегая к перезапуску приложения.
Может следовало посмотреть в похожую реализацию в данной библиотеке?

**Comment by alexander-akhmetov** [comment]
Возможно. `python-telegram` изначально создавался как просто интерфейс к tdlib, может быть контроль на уровне приложения которое использует эту библиотеку является более явным решением в данном случае, а может и нет.
