### ISSUE TITLE
queue.Full is raised after a while

### ISSUE THREAD

**Issue by JonesH** [alexander-akhmetov/python-telegram#169]
After running for a while, queue.Full is raised, leaving the client in a state where it wouldn't process any more updates.

**Comment by alexander-akhmetov** [comment]
Do you have any other errors in the logs? The default implementation uses one single threaded worker to process the requests and the client doesn't restart in case of errors.

**Comment by JonesH** [comment]
Yes, might that be the problem? The thread with the handler crashes, so the program stops handling updates, resulting in queue.Full?

**Comment by JonesH** [comment]
Alright, handling the error properly seems to have solved the issue. Thank you!
