### ISSUE TITLE
bot login

### ISSUE THREAD

**Issue by naser** [alexander-akhmetov/python-telegram#17]
Is it possible to login using bot tokens, instead of phone numbers? I see it exists in the tdlib but not in your wrapper.

**Comment by naser** [comment]
I did it actually!
will upload it as a pull request.

**Comment by alexander-akhmetov** [comment]
It would be great 👍

**Comment by peterus** [comment]
any update on this? would need the same.

**Comment by Kylmakalle** [comment]
@naser bumping this request, I also want to see some code about bot login.
