### ISSUE TITLE
libssl.so.1.1: cannot open shared object file

### ISSUE THREAD

**Issue by dtypo** [alexander-akhmetov/python-telegram#172]
Hello :)
I'm trying to execute the sample script provided on my nas (DS920+) with python installed.

    from telegram.client import Telegram
    
    tg = Telegram(
        api_id='myid',
        api_hash='myhash',
        phone='myphone',  # you can pass 'bot_token' instead
        database_encryption_key='mykey',
    )
    tg.login()
    
    # if this is the first run, library needs to preload all chats
    # otherwise the message will not be sent
    result = tg.get_chats()
    result.wait()
    
    result = tg.send_message(
        chat_id=args.chat_id,
        text=args.text,
    )
    # `tdlib` is asynchronous, so `python-telegram` always returns you an `AsyncResult` object.
    # You can receive a result with the `wait` method of this object.
    result.wait()
    print(result.update)
    
    tg.stop()  # you must call `stop` at the end of the script

But I got this annoying error.
I've seen something similar in the issue #4 , but not my case unfortunately :/

    Traceback (most recent call last):
      File "test.py", line 3, in <module>
        tg = Telegram(
      File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/telegram/client.py", line 130, in __init__
        self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
      File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/telegram/tdjson.py", line 27, in __init__
        self._build_client(library_path, verbosity)
      File "/var/packages/py3k/target/usr/local/lib/python3.8/site-packages/telegram/tdjson.py", line 36, in _build_client
        self._tdjson = CDLL(library_path)
      File "/var/packages/py3k/target/usr/local/lib/python3.8/ctypes/__init__.py", line 373, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libssl.so.1.1: cannot open shared object file: No such file or directory

As expected, a trivial `pip install pyopenssl` didn't solve my problem.
Can someone help?

**Comment by alexander-akhmetov** [comment]
If you're using the built-in tdlib, you need to install `openssl` (1.1)

You can also compile tdlib youself and link it against another version, or build a docker image. Current Dockerfile uses [python:3.8.1-slim-buster](https://hub.docker.com/_/python?tab=tags&page=1&ordering=last_updated&name=3.8.1-slim-buster) which also has an arm image.

**Comment by dtypo** [comment]
> If you're using the built-in tdlib, you need to install `openssl` (1.1)
> 
> You can also compile tdlib youself and link it against another version, or build a docker image. Current Dockerfile uses [python:3.8.1-slim-buster](https://hub.docker.com/_/python?tab=tags&page=1&ordering=last_updated&name=3.8.1-slim-buster) which also has an arm image.

Thanks for the quick reply alexander :)
In my Synology an `dtypo@synology:~$ openssl version` gives me `OpenSSL 1.0.2u-fips  20 Dec 2019`.
Unfortunately the native Syno environment doesn't provide a proper package manager, so I suppose to be stuck with that precise version of openssl :(
I suppose the most painless way is using Docker.
Thanks for the help :)
