### ISSUE TITLE
Can not import Telegram from telegram.clients under windows python 3.9

### ISSUE THREAD

**Issue by burakertr** [alexander-akhmetov/python-telegram#185]
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from telegram.client import Telegram
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\telegram\client.py", line 42, in <module>
    class Telegram:
  File "C:\Python39\lib\site-packages\telegram\client.py", line 480, in Telegram
    self, stop_signals: Tuple = (signal.SIGINT, signal.SIGTERM, signal.SIGABRT, signal.SIGQUIT)
AttributeError: module 'signal' has no attribute 'SIGQUIT'

I got this error. How to solve this. Even simple tutorial not working.

**Comment by alexander-akhmetov** [comment]
Hi. The library does not support Windows
