### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by davidcon** [alexander-akhmetov/python-telegram#199]
I have used pip to install in conda enviroment:

`pip install python-telegram
`

But when I try to run the example it reports the following error:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c02d23bd28fd> in <module>
----> 1 from telegram.client import Telegram
      2 
      3 tg = Telegram(
      4     api_id='api_id',
      5     api_hash='api_hash',

ModuleNotFoundError: No module named 'telegram'
```
Do I have to install any thing else?

Thank you very much!

**Comment by Borisd93** [comment]
You need to use pip3 because conda have's 2 version's of python.
