### ISSUE TITLE
ImportError: cannot import name 'setup_logging' from 'utils'

### ISSUE THREAD

**Issue by btcdw** [alexander-akhmetov/python-telegram#205]
I copied the code directly from github and got an error

ImportError: cannot import name 'setup_logging' from 'utils' (C:\Users\btcdw\PycharmProjects\电报自动聊天\venv\lib\site-packages\utils\__init__.py)

https://github.com/alexander-akhmetov/python-telegram/blob/master/examples/send_message.py

**Comment by alexander-akhmetov** [comment]
Hi, the example uses [utils.py](https://github.com/alexander-akhmetov/python-telegram/blob/master/examples/utils.py) which you must copy to the same directory with send_message.py

**Comment by twilight-slider** [comment]
where i can find `setup_logging` method?
