### ISSUE TITLE
Can't send inputFileLocal. Error: "InputFile is not specified"  

### ISSUE THREAD

**Issue by Smarandii** [alexander-akhmetov/python-telegram#218]
I'm trying to call method "setProfilePhoto", but got error:
`"InputFile is not specified"`

My code:

```python
p = {"photo": {"@type":"inputChatPhotoStatic",
            "photo_": {"@type": "inputFileLocal", "path_": "photo.jpg"}}}

result = tg.call_method(method_name="setProfilePhoto", params=p)
result.wait()
```

What's wrong?

**Comment by Smarandii** [comment]
with "inputFileRemote" didn't worked either:
p = {"photo": {"@type":"inputChatPhotoStatic",
            "photo_": {"@type": "inputFileRemote", "id_": "file_id"}}}

result = tg.call_method(method_name="setProfilePhoto", params=p)
result.wait()

**Comment by shironoY6** [comment]
Probably you just need to remove the trailing underscore from `photo_` and `id_` in your parameter dictionary.

```
p = {"photo": {"@type":"inputChatPhotoStatic",
            "photo": {"@type": "inputFileLocal", "path": "profile_photo.png"}}}

result = tg.call_method(method_name="setProfilePhoto", params=p)
result.wait()
```
This worked for me.


```
data = {
    '@type': 'setProfilePhoto',
    'photo': {
        '@type': 'inputChatPhotoStatic',data = {
    '@type': 'setProfilePhoto',
    'photo': {
        '@type': 'inputChatPhotoStatic',
        'photo': {
            "@type": "inputFileLocal",
            "path":  "profile_photo.png"
        }
    }
}
r = tg._send_data(data)
        'photo': {
            "@type": "inputFileLocal",
            "path":  "profile_photo.png"
        }
    }
}
r = tg._send_data(data)
```
Here is a tdjson example of the same.

**Comment by Smarandii** [comment]
> Probably you just need to remove the trailing underscore from `photo_` and `id_` in your parameter dictionary.
> 
> ```
> p = {"photo": {"@type":"inputChatPhotoStatic",
>             "photo": {"@type": "inputFileLocal", "path": "profile_photo.png"}}}
> 
> result = tg.call_method(method_name="setProfilePhoto", params=p)
> result.wait()
> ```
> This worked for me.
> 
> 
> ```
> data = {
>     '@type': 'setProfilePhoto',
>     'photo': {
>         '@type': 'inputChatPhotoStatic',
>         'photo': {
>             "@type": "inputFileLocal",
>             "path":  "profile_photo.png"
>         }
>     }
> }
> r = tg._send_data(data)
> ```
> Here is a tdjson example of the same.

That worked for me as well, thanks a lot!
