### ISSUE TITLE
error in terminal

### ISSUE THREAD

**Issue by Mohammadwh** [alexander-akhmetov/python-telegram#22]
[ 1][t 1][1553186089.422070026][MessagesManager.cpp:21569][!Td] Have full history in chat -1001081163428, but receive unknown server message 322600 from get history. Last new is server message 326099, last is server message 319292, first database is server message 1, last database is server message 319292, last read inbox is server message 326099, last read outbox is server message 326099, last read all mentions is invalid message 0, max unavailable is invalid message 0, last assigned is invalid message 0

hello 
my bot print this error and change status to offline 
how i can fix this problem :(

**Comment by peterus** [comment]
Can you post your example code?
