### ISSUE TITLE
Exception has occurred: RuntimeError

### ISSUE THREAD

**Issue by atrezonator** [alexander-akhmetov/python-telegram#227]
I'm having the problem on the first access, when login

Telegram error: {'@type': 'error', 'code': 406, 'message': 'UPDATE_APP_TO_LOGIN', '@extra': {'request_id': 'updateAuthorizationState'}}
  File "/opt/bots/test/main.py", line 12, in <module>
    tg.login()

**Comment by AYMENJD** [comment]
You are using outdated version of tdlib, re-build tdlib then specify libtdjson.so path.

**Comment by gibranlamarca** [comment]
I'm having the same issue, have something to do with the new requirement of int64 IDs instead of 32 from telegram, updated yesterday

**Comment by alexander-akhmetov** [comment]
It is indeed an issue with the old tdlib version. `python-telegram` 0.14.0 uses tdlib 1.7.0 which is unsupported. I've released a new version of python-telegram (0.15.0), it uses tdlib v1.7.9 and should work.

**Comment by alexander-akhmetov** [comment]
Please, reopen if it still fails with `0.15.0`
