### ISSUE TITLE
I'm having the same issue, have something to do with the new requirement of int64 IDs instead of 32 from telegram, updated yesterday

### ISSUE THREAD

**Issue by MaxDXDX** [alexander-akhmetov/python-telegram#228]
I'm having the same issue, have something to do with the new requirement of int64 IDs instead of 32 from telegram, updated yesterday

_Originally posted by @gibranlamarca in https://github.com/alexander-akhmetov/python-telegram/issues/227#issuecomment-984606716_

Yes, I'm having the same issue.

**Comment by alexander-akhmetov** [comment]
Please, see #227
