### ISSUE TITLE
Runtime Error with 0.15.0

### ISSUE THREAD

**Issue by gibranlamarca** [alexander-akhmetov/python-telegram#229]
RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 406, 'message': 'UPDATE_APP_TO_LOGIN', '@extra': {'request_id': 'updateAuthorizationState'}
![image](https://user-images.githubusercontent.com/70969354/144632416-0aa556d8-9bff-44c4-b06e-5f34a8d68160.png)

**Comment by alexander-akhmetov** [comment]
Hi! Can you please confirm that it uses tdlib v1.7.9? You can set `tdlib_verbosity` to `4`:

```python
tg = Telegram(
    ...
    tdlib_verbosity=4,
)
```

And after that tdlib will start logging more verbose information. Search for `Sending update: updateOption`, it should be in the beginning of the log and should look like this:

```
[Td.cpp:4274][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.7.9"
  }
}
```

**Comment by gibranlamarca** [comment]
Hi! First of all thank you for the fast response. I did the settings but nothing seems to be changing, couldn't find that log:
![image](https://user-images.githubusercontent.com/70969354/144639248-7d49f2b2-7c39-4c2b-97ec-25aab0a257c1.png)

**Comment by alexander-akhmetov** [comment]
Are you sure that you are running the latest code with the change, maybe you need to rebuild the image or mount the local folder?

**Comment by gibranlamarca** [comment]
Oh my bad, I got it now. It's using 1.7.9 indeed, but now I'm receiving another error, as it follows on image:
[ 3][t 4][1638555254.453232049][Td.cpp:4274][#1][!Td][&td_requests]     Sending update: updateOption {
  name = "version"
  value = optionValueString {
    value = "1.7.9"
  }
}

![image](https://user-images.githubusercontent.com/70969354/144652627-ed9ea018-ddf9-47e0-9808-56a6d4372f03.png)

**Comment by gibranlamarca** [comment]
Oh that was my bad @alexander-akhmetov! Now everything is working just fine. Thanks for the support
