### ISSUE TITLE
function calls

### ISSUE THREAD

**Issue by peterus** [alexander-akhmetov/python-telegram#23]
Currently there are some functions (get_me(), get_chat(), get_chats(), ...) implemented in client.py, some functions can be called via the call_method() function.
How do you plane to have this in the future? do you want to have all functions implemented?
maybe split up in two py-files: one for functions which can be used for the bot, the other one for normal API functions.
I could give you a hand with this.

**Comment by alexander-akhmetov** [comment]
Hi,

The idea was to have a generic method `call_method` and to write simplified versions of all other methods. Ideally, the library should support all `tdlib` methods. I'm not sure that it's worth to split the client class into two different files, at least not now.

**Comment by peterus** [comment]
Hi Alex! Thanks for your answer.
Are you ok if i add step-by-step the functions to client.py?

**Comment by alexander-akhmetov** [comment]
Sure, that would be great :) Don't forget to add tests, please :)

**Comment by alexander-akhmetov** [comment]
> How do you plane to have this in the future? do you want to have all functions implemented?

Ideally, I think, it would be great to have auto-generated methods to call `tdlib`

**Comment by RomanKoshkin** [comment]
Hi, Is it possible to call the `messages.createChat` method from the telegram API using this library? If so, can you please provide a minimalistic example?

**Comment by alexander-akhmetov** [comment]
> Hi, Is it possible to call the `messages.createChat` method from the telegram API using this library? If so, can you please provide a minimalistic example?

Hi, yes, it's possible  to call any method using `Telegram.call_method`:

```python

tg = Telegram(...)

params = {
    'user_id': 123,
}
tg.call_method('createPrivateChat', params=params)
```

I haven't tested the code, but the idea is that you can use `call_method` to call any `tdlib` method.
