### ISSUE TITLE
messages stuck in the queue

### ISSUE THREAD

**Issue by alec-djinn** [alexander-akhmetov/python-telegram#231]
This is a bit hard to describe since no errors are raised.

The code used is adapted from the tutorial and it should simply send a message to a chat.

The problem is that when I first run the script, to send `message_1`, no message is sent.
If I run the script a second time sending `message_2`, then `message_1` is delivered instead (the previous message!),
if I again run the script, with `another_message`, then `messae_2` is delivered (the previous message again!). 

It looks like the message queue is one message off but I am not sure what is going wrong, the code is pretty simple.

The code I run in a Jupyter notebook for test:

```
out = subprocess.check_output(
    f'python tg_send.py --msg {msg} --chat {chat_id} --id {api_id} --hash {api_hash} --phone {phone}',
    shell=True
)
print(out)
```

tg_send.py 
```
from telegram.client import Telegram
import argparse


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--msg", type=str, required=True, help="the message body")
    parser.add_argument("--chat", type=str, required=True, help="message destination")
    parser.add_argument("--phone", type=str, required=True, help="phone number of the sender")
    parser.add_argument("--id", type=str, required=True, help="Telegram App api_id")
    parser.add_argument("--hash", type=str, required=True, help="Telegram App api_hash")
    

    args = parser.parse_args()

    tg = Telegram(
        api_id = args.id,
        api_hash = args.hash,
        phone = args.phone,
        database_encryption_key="changekey123" 
    )
    
    tg.login()

    # if this is the first run, library needs to preload all chats
    # otherwise the message will not be sent
    result = tg.get_chats()
    result.wait()

    if result.error:
        print(f'get chats error: {result.error_info}')
    else:
        print(f'chats: {result.update}')


    result = tg.send_message(
        chat_id = args.chat,
        text = args.msg,
    )

    result.wait()
    if result.error:
        print(f'send message error: {result.error_info}')
    else:
        print(f'message has been sent: {result.update}')
    
    tg.stop()
            
    print('DONE')
```

**Comment by alexander-akhmetov** [comment]
Hi! `python-telegram` sends the message to the tdlib instance, gets the confirmation that the message was received by tdlib, but it might be that the application stops before tdlib has time to actually send the message. You can try to add some sleep before `tg.stop()` and increase logging verbosity to check that:

```
tg = Telegram(
    ...,
    tdlib_verbosity=7,
)
```
