### ISSUE TITLE
Launch on  Ubuntu 16.04.7 LTS

### ISSUE THREAD

**Issue by mihmig** [alexander-akhmetov/python-telegram#235]
What operating system can the client run on?
When I start it on ubuntu 16.04.7 LTS, I get the error:
OSError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /usr/local/lib/python3.9/dist-packages/telegram/lib/linux/libtdjson.so)

**Comment by alexander-akhmetov** [comment]
Hi! tdlib in python-telegram `0.15.0` (tdlib `1.7.9`) is built on Ubuntu 20.04 (x86-64).

You can build your own tdlib and use it with the client. Build the library following the instructions [here](https://tdlib.github.io/td/build.html), and then specify path to `libtdjson.so`:

```python
Telegram(
    ...
    library_path='/path/to/libtdjson.so',
)
```
