### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by F-15023** [alexander-akhmetov/python-telegram#240]
Hello, I am trying to download file that received in messages, but can't to do it. 
file_id = 638 for example

        params = {"file_id": file_id, "priority": 30, "offset": 0, "limit": 0, "synchronous": "true"}
        result = self.tg.call_method("downloadFile", params)
        result.wait()
        print(result.update)

It returns None. What I am doing wrong?

**Comment by alexander-akhmetov** [comment]
Hi! Check out [this comment](https://github.com/alexander-akhmetov/python-telegram/issues/78#issuecomment-591636468) please, it might help.
