### ISSUE TITLE
The right way to handle errors (esp. flood_wait_ )?

### ISSUE THREAD

**Issue by Victornovikov** [alexander-akhmetov/python-telegram#25]
Hi all,

I am trying to fetch messages from a bunch of public channels and eventually start hitting "FLOOD_WAIT_" errors.

Do you mind sharing what is the best way to catch those errors (so that script pauses sending requests)?

Thank you.

**Comment by alexander-akhmetov** [comment]
Hi,

The library doesn't provide any mechanism to handle these errors, you have to catch them manually and pause the script on your side. You can check `AsyncResult.error_info`, it should contain details of the error

**Comment by Victornovikov** [comment]
Perfect, thanks. 

For those who missed it just how I did, there is an example [here](https://github.com/alexander-akhmetov/python-telegram/blob/91d577e75f7dbfe022fe9085f2a7bacef6712ee2/examples/send_message.py)
