### ISSUE TITLE
Can you help me - I just want to forward messages when they are edited (2-3 sec later)

### ISSUE THREAD

**Issue by oscarstv** [alexander-akhmetov/python-telegram#254]
Hello,
I'm using https://github.com/radinshayanfar/TGCopyBot/blob/master/app/main.py, based upon your work. It forwards messages from a channel to another one.
This is the part of the code that does that:
```
def copy_message(from_chat_id: int, message_id: int, send_copy: bool = True) -> None:
    data = {
        'chat_id': dst_chat,
        'from_chat_id': from_chat_id,
        'message_ids': [message_id],
        'send_copy': send_copy,
    }
    result = tg.call_method(method_name='forwardMessages', params=data, block=True)
    # print(result.update)

```

```
def new_message_handler(update):
    # To print every update:
    # print(update)
```

    # We want to process only new messages
    if 'sending_state' in update['message']:
        return

    message_chat_id = update['message']['chat_id']
    message_id = update['message']['id']

    # We want to process only messages from specific channel
    if message_chat_id != src_chat:
        return

    # Check if message is forwarded
    if 'forward_info' in update['message']:
        copy_message(message_chat_id, message_id, False)
    else:
        copy_message(message_chat_id, message_id)
`

Do you know how I could modify it to get forwarded only the messages that are edited?
Thank you!

PS Another solution could be sending an edited message as it was a new message.
PS2: My problem is: I want to forward a message from a channel that always does the next:
1) A dot character is sent as a message.
2) Then the message with the dot character is edited and created a new one (2-3 seconds later).
3) I need to forward only the edited message, that is, the second version, not the dot.
PS3: Another solution could be:
a) Get the message.
b) Wait for 3-4 seconds.
c) get the updated message, and send it. Is this possible?

**Comment by shironoY6** [comment]
maybe you can set up an event handler for `updateMessageEdited`?

https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1update_message_edited.html

I wanted to do something similar too. Let me know if you made a progress!
If I find the time, I will have a look into this as well.
