### ISSUE TITLE
Language translation method? 

### ISSUE THREAD

**Issue by victorccaldas** [alexander-akhmetov/python-telegram#258]
I see that Telegram has a translation function, is it accessible through this wrapper or are there any intentions to implement it? I'm not a great C++ understander, but a quick search on the tdlib official repo showed me what it seems to be this function : https://github.com/tdlib/td/search?q=translate

**Comment by alexander-akhmetov** [comment]
Hi! Sorry for the late response. If tdlib exposes this function, it might be possible to call it with the generic [call_method](https://github.com/alexander-akhmetov/python-telegram/blob/7e11953c920e1454b0a54afaf8dd3f03319148a3/telegram/client.py#L376), but I don't know how to do this.
