### ISSUE TITLE
how to fix stop method bug 

### ISSUE THREAD

**Issue by Mohammadwh** [alexander-akhmetov/python-telegram#26]
hello how i can fix stop method bug?
is ok in release in 8.0 version?

**Comment by alexander-akhmetov** [comment]
Hi, no, it's not fixed in the `0.8.0`: https://github.com/alexander-akhmetov/python-telegram/issues/8

**Comment by alexander-akhmetov** [comment]
Fixed in version [0.9.0(https://python-telegram.readthedocs.io/en/latest/changelog.html)
