### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by shosaman** [alexander-akhmetov/python-telegram#27]

**Comment by shosaman** [comment]
Dear Alex,
I have successfully installed your "python-telegram" python3 -m pip install python-telegram code on my ubuntu 18.0.4 64 bit.
Then I took your basic tutorial and trying to run. The tutorial file is as follows:

=========================================================
from telegram.client import Telegram

print("Before Telegram call")
tg = Telegram(
    api_id=724167,
    api_hash='my hash key',
    phone='+917702857001',
    database_encryption_key='test_key',
)
print("Before Login call")
tg.login()
print("After Login call")
def new_message_handler(update):
    print('New message!')

tg.add_message_handler(new_message_handler)
tg.idle()  # blocking waiting for CTRL+C
==========================================
I then run 

python3 ./mysecond.py

This program results in Segmentation Error (Core Dumped) 

shosaman@IQ301-HP-Laptop-0004:~/bin$ 
shosaman@IQ301-HP-Laptop-0004:~/bin$ python3 mysecond.py 
Before Telegram call
Segmentation fault (core dumped)
shosaman@IQ301-HP-Laptop-0004:~/bin$ 

WHat could be going wrong ? Please help.

**Comment by shosaman** [comment]
If you see the message "Before Telegram call" gets printed on the screen
However Before Login call" does not get printed..
Hence I'm assuming in the Telegram() call it is getting core dump.

Please help me understand what I can do to make this run successfully. Thank you ;

**Comment by alexander-akhmetov** [comment]
Hi,

I guess it’s because of the incorrectly compiled `tdlib` in the library. If you use the latest `0.8.0`, can you try to do the same with version `0.7.0`?

Also, you can compile tdlib and pass path to it as a parameter to the `Telegram`:

```shell
tg = Telegram(library_path='...')
```

**Comment by shosaman** [comment]
Thank you Alex. I had also tried passing the path using library_path parameter.
However I did not know if it was due to 0.8.0 version.
I'll use the 0.7.0 and will try and will write back. 
Thnk you for your response. Appreciate it.

**Comment by alexander-akhmetov** [comment]
Hi, you also can try the latest `0.10.0`, it is compiled for ubuntu

**Comment by shosaman** [comment]
Wow! So nice of you sir. Sure, I'll try this version thank you.

________________________________

**Comment by alexander-akhmetov** [comment]
Please, re-open the issue if you still have the problem
