### ISSUE TITLE
Experiencing libcrypto issue on Ubuntu 22.04

### ISSUE THREAD

**Issue by brookmg** [alexander-akhmetov/python-telegram#282]
Getting the following error when running the sample code in the README.md

```
OSError: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/local/lib/python3.10/dist-packages/telegram/lib/linux/libtdjson.so)
```

**Comment by F-15023** [comment]
Hello, I have a proplems in Ubuntu 22 too, but other one.
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
Just doing this:
tg = Telegram(api_id=API_ID,
              api_hash=API_HASH,
              phone=PHONE, 
              database_encryption_key="qwerty123",
              files_directory=os.getcwd())
tg.login()

**Comment by luk0y** [comment]
> 



> Getting the following error when running the sample code in the README.md
> 
> ```
> OSError: /lib/x86_64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by /usr/local/lib/python3.10/dist-packages/telegram/lib/linux/libtdjson.so)
> ```

I also faced this issue. Actually the path is not referenced correctly to 'libcrypto.so.1.1'. I found this file in '`/usr/local/lib`' and added a new line in `/etc/ld.so.conf` as '`include /usr/local/lib`'. Then I reloaded using '`sudo ldconfig`'. Try this and let me know.

**Comment by TheonlyJ** [comment]
Hi! I'm experiencing the same on macOS Ventura 13.3 (M1). I have openssl installed via homebrew, so I have
```
which openssl
/opt/homebrew/bin/openssl
```

but when I try to use python-telegram, I get 
```
OSError: dlopen(blah blah/venv/lib/python3.8/site-packages/telegram/lib/darwin/libtdjson.dylib, 0x0006): Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: <0168E972-B06F-3F12-8075-8194AFD09961> blah blah/venv/lib/python3.8/site-packages/telegram/lib/darwin/libtdjson.dylib
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file, not in dyld cache)
```

How do I fix this?
