### ISSUE TITLE
tgcall

### ISSUE THREAD

**Issue by mehdigudrazi** [alexander-akhmetov/python-telegram#284]
I've got 2 questions to ask, how can I use tgcall on this wrapper and how can i make Json-ld like message if u can't tell ,  tg.call_method  cannot  shape the  message the way it should does

**Comment by alexander-akhmetov** [comment]
Hi! I don't think it's possible to use tgcall with this wrapper. 

> how can i make Json-ld like message

Sorry, what do you mean?
