### ISSUE TITLE
OSError: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kaxap** [alexander-akhmetov/python-telegram#3]
Getting this 

```
OSError: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
```

 with [tutorial](https://python-telegram.readthedocs.io/en/latest/tutorial.html) example on Ubuntu 16.04

**Comment by kaxap** [comment]
Can be fixed with

```bash
apt-get install musl-dev
```
And then

```bash
ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
```

**Comment by alexander-akhmetov** [comment]
Hi!

Thank you, I will update the documentation

**Comment by ELTR11** [comment]
send as file/link to file pls

**Comment by hanskokx** [comment]
> Can be fixed with
> 
> ```shell
> apt-get install musl-dev
> ```
> 
> And then
> 
> ```shell
> ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
> ```

My issue wasn't with telegram, but this was the only useful bit of information I found.  Thank you!

**Comment by nikos445** [comment]
I was trying to run tests that include: Jest + Supertest + Express + MongoDB + BCRYPT 

on Gitlab CI and you made my DAY! :) 

THANK YOU MATE! 👍🏼 🍺
