### ISSUE TITLE
Disable log messages

### ISSUE THREAD

**Issue by MaxDXDX** [alexander-akhmetov/python-telegram#306]
Hi guys!

I'd like to turn off inner colored TDLib log messages in console such as:
`[ 2][t 4][1660821640.573203086][AuthDataShared.cpp:107][#1][!Td]`
`[ 2][t 4][1660821648.668215036][Td.cpp:3597][#1][!Td]   Close Td in state 2`
`Generate new session_id 8046556961038579337 for auth key 18393559095990870397 for main DC2`
and etc.

I have looked for any code in `python-telegram` package `*.py` files, but don't find any snippets that responsible for this logging messages. I found standard python logger only.

How to disable above messages?

**Comment by alexander-akhmetov** [comment]
Hi! You can try to set `tdlib_verbosity` (default: 2) to a lower value: `Telegram(tdlib_verbosity=...)`

**Comment by MaxDXDX** [comment]
> Hi! You can try to set `tdlib_verbosity` (default: 2) to a lower value: `Telegram(tdlib_verbosity=...)`

Exactly what I want! I am grateful for your support, Alexander!
