### ISSUE TITLE
Finding database_encryption_key

### ISSUE THREAD

**Issue by kuzeyron** [alexander-akhmetov/python-telegram#31]
Hello! I find it strange that I cannot find anything regarding the `database_encryption_key`.
Where do I get or set that part? The rest is under control but not this part.
In Telegram's doc they say I can leave it empty. But I'm not sure if it's okay with this app.

**Comment by kuzeyron** [comment]
Solved it by changing the calls.

**Comment by LeonardoRick** [comment]
Hi @kuzeyron, have you found more info about that?

**Comment by kuzeyron** [comment]
Hey @LeonardoRick, It's been some time since I was working on this one.
Do you mind sharing the code and your error messages? In case it triggers my memory.
