### ISSUE TITLE
Adding params for tdlight support

### ISSUE THREAD

**Issue by dwap** [alexander-akhmetov/python-telegram#310]
https://github.com/tdlight-team/tdlight#tdlight-extra-options

**Comment by drzraf** [comment]
Could you please explain where TDLib was sourced from? source code says 1.8.5 but no such version exist officially in GitHub AFAICT

**Comment by alexander-akhmetov** [comment]
Hi! It does exist: https://github.com/tdlib/td/commit/d9cfcf88fe4ad06dae1716ce8f66bbeb7f9491d9, there just no tag.

**Comment by alexander-akhmetov** [comment]
The library does not support tdlight.
