### ISSUE TITLE
use `tg.send_message` Too Many Requests

### ISSUE THREAD

**Issue by codewc** [alexander-akhmetov/python-telegram#313]
`[ 2][t 1][1663253540.292405605][NetQueryDelayer.cpp:73][#1][!NetQueryDelayer]	Failed: [Query:[id:3801088][tl:0x520c3870][state:Query]] [timeout:291.000000][total_timeout:296.000000] because of [Error : 420 : FLOOD_WAIT_291] from Session:5:main::Connect::Tcp::[91.108.56.111:443] to DcId{5} from [172.18.0.2:42144]
[ 2][t 1][1663253540.293200969][SequenceDispatcher.cpp:56][#1][!sequence dispatcher]	Fail [Query:[id:3866624][tl:0x520c3870][state:Query]] to  because total_timeout 291.000000 is greater than total_timeout_limit 60.000000
[ 2][t 1][1663253540.293818950][MessagesManager.cpp:30024][#1][!net_actor][&error_code != 403]	Fail to send yet unsent message 92018.249 in chat -646110821 with the error [Error : 429 : Too Many Requests: retry after 291]
[ 2][t 1][1663253540.294599056][SequenceDispatcher.cpp:56][#1][!sequence dispatcher]	Fail [Query:[id:3932160][tl:0x520c3870][state:Query]] to  because total_timeout 291.000000 is greater than total_timeout_limit 60.000000
[ 2][t 1][1663253540.295736074][MessagesManager.cpp:30024][#1][!net_actor][&error_code != 403]	Fail to send yet unsent message 92018.257 in chat -646110821 with the error [Error : 429 : Too Many Requests: retry after 291]
[ 2][t 1][1663253540.296506166][SequenceDispatcher.cpp:56][#1][!sequence dispatcher]	Fail [Query:[id:3997696][tl:0x520c3870][state:Query]] to  because total_timeout 291.000000 is greater than total_timeout_limit 60.000000
[ 2][t 1][1663253540.297366857][MessagesManager.cpp:30024][#1][!net_actor][&error_code != 403]	Fail to send yet unsent message 92018.265 in chat -646110821 with the error [Error : 429 : Too Many Requests: retry after 291]
[ 2][t 1][1663253540.298449993][SequenceDispatcher.cpp:56][#1][!sequence dispatcher]	Fail [Query:[id:4063232][tl:0x520c3870][state:Query]] to  because total_timeout 291.000000 is greater than total_timeout_limit 60.000000
[ 2][t 1][1663253540.299255609][MessagesManager.cpp:30024][#1][!net_actor][&error_code != 403]	Fail to send yet unsent message 92018.273 in chat -646110821 with the error [Error : 429 : Too Many Requests: retry after 291]
[ 2][t 1][1663253540.300059080][SequenceDispatcher.cpp:56][#1][!sequence dispatcher]	Fail [Query:[id:4128768][tl:0x520c3870][state:Query]] to  because total_timeout 291.000000 is greater than total_timeout_limit 60.000000
[ 2][t 1][1663253540.300646781][MessagesManager.cpp:30024][#1][!net_actor][&error_code != 403]	Fail to send yet unsent message 92018.281 in chat -646110821 with the error [Error : 429 : Too Many Requests: retry after 291]
[ 2][t 1][1663253540.301627635][SequenceDispatcher.cpp:56][#1][!sequence dispatcher]	Fail [Query:[id:4194304][tl:0x520c3870][state:Query]] to  because total_timeout 291.000000 is greater than total_timeout_limit 60.000000`

**Comment by alexander-akhmetov** [comment]
Hi! These messages are from tdlib, as far as I understand it automatically retries and sends the messages later (`retry after 291`)
