### ISSUE TITLE
session is stoped but cpu is full use!

### ISSUE THREAD

**Issue by Mohammadwh** [alexander-akhmetov/python-telegram#32]
hello 
i test bot_login.py
session is stoped but cpu is 100%
![Capture](https://user-images.githubusercontent.com/18552903/57075090-0819a400-6cfb-11e9-9688-c375c15bb9b3.PNG)

**Comment by alexander-akhmetov** [comment]
Hi, does it happen after `tg.stop()` (Is `None` the output of [this line](https://github.com/alexander-akhmetov/python-telegram/blob/master/examples/bot_login.py#L18)?)?

**Comment by Mohammadwh** [comment]
hello my problem not is None update
client is stoped but cpu usage is not normal

**Comment by alexander-akhmetov** [comment]
Can you please give more details? Do you run the `examples/bot_login.py` or some modified code? 
If the former, it should print the result of `get_me` function and stop.

**Comment by alexander-akhmetov** [comment]
I'm closing this for now, if it's still happens, please, re-open the issue.
