### ISSUE TITLE
please add send media example, Thank you in advance.

### ISSUE THREAD

**Issue by heitumo** [alexander-akhmetov/python-telegram#328]
please add send media, like video, picture and voice.  Thank you in advance.

**Comment by tbscode** [comment]
Also wondering about this, I've tried using the `sendPhoto` api via `call_method` without success.

e.g.:
```
    data = {'chat_id': chat_id,
            'photo': url, 'caption' : message}

    tg.call_method('sendPhoto', data)
```

**Comment by tbscode** [comment]
Ok looked a little at the source code and api and it would prob rater be something like this:

```python
data = {
    'chat_id': chat_id,
    'input_message_content': {
        '@type': 'inputMessagePhoto',
        'photo': {
            '@type': 'inputFileLocal', # https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1input_file_local.html
            'path': file_path,
        },
    },
}
tg.call_method('sendMessage', data)
```

I'll check later if I can get it to work.

**Comment by alexander-akhmetov** [comment]
Hi! Yes, sorry, there is no example in the documentation yet. @tbscode's code should work, a couple of years ago I mentioned the internal `_send_data` [here](_send_data) method but `call_method` is better and easier to use.

**Comment by tbscode** [comment]
Ah I checked the issues must have overlooked that one, thanks. I've tested it now and yes I can confirm it works.
