### ISSUE TITLE
Session File missing

### ISSUE THREAD

**Issue by yoroi-dev-product** [alexander-akhmetov/python-telegram#336]
Hi, is there a way to retrieve the session file like the telethon library does?

The issue here is that i want my session to be portable (ex: in case of dockerization) so I dont have to enter the auth code all the times..

**Comment by alexander-akhmetov** [comment]
Hi! By default the library [keeps the session related files in /tmp](https://github.com/alexander-akhmetov/python-telegram/blob/50871c91c63a0800681e2c336fb2ee18e4954c75/telegram/client.py#L119), but you can change this:

```
tg = Telegram(
    ...
    files_directory='/tmp/.tdlib_files/',
)
```
