### ISSUE TITLE
AttributeError: module 'utils' has no attribute 'setup_logging'

### ISSUE THREAD

**Issue by twilight-slider** [alexander-akhmetov/python-telegram#338]
Privet
trying to execute this
https://github.com/alexander-akhmetov/python-telegram/blob/master/examples/get_me_non_blocking_login.py

have copied utils.py 
https://github.com/alexander-akhmetov/python-telegram/blob/master/telegram/utils.py
to the same folder
but on docker build-run-logs i got AttributeError: module 'utils' has no attribute 'setup_logging'
therу is no 'setup_logging' in 'utils.py'

**Comment by twilight-slider** [comment]
ok a found another utils.py - in examples)

**Comment by alexander-akhmetov** [comment]
Hi! Yes, there is an `utils.py` in the examples folder :)
