### ISSUE TITLE
sending images

### ISSUE THREAD

**Issue by MalteToenjes** [alexander-akhmetov/python-telegram#34]
Hey, currently its not possible to send images or? Do you know if its possible with tdlib?

**Comment by alexander-akhmetov** [comment]
Yes, it is possible with `tdlib` but is not implemented in the `python-telegram` yet.

I would not recommend using this, but photos and documents can be sent using the private method `Telegram._send_data`:

**Document**

```python
data = {
    '@type': 'sendMessage',
    'chat_id': chat_id,
    'input_message_content': {
        '@type': 'inputMessageDocument',
        'document': {'@type': 'inputFileLocal', 'path': '/Users/iam/my_file.txt'},
    },
}

result = tg._send_data(data)
```

**Photo**

```python
data = {
    '@type': 'sendMessage',
    'chat_id': chat_id,
    'input_message_content': {
        '@type': 'inputMessagePhoto',
        'photo': {'@type': 'inputFileLocal', 'path': '/Users/iam/my_photo.png'},
    },
}


result = tg._send_data(data)
```

**Comment by MalteToenjes** [comment]
Ok Thanks, it worked well so far....but why you wouldn't recommend it?

**Comment by alexander-akhmetov** [comment]
It's a private method so it can be changed in the future. I think we need a generic method to call  `tdlib` with any json.
