### ISSUE TITLE
echo_bot.py | sender_id = 0 and negative chat_id for channel conversation threads

### ISSUE THREAD

**Issue by osamajameelahmad** [alexander-akhmetov/python-telegram#36]
Hello,
I am using echo_bot.py for getting messaging. I am getting sender_id = 0 in case channel thread and also chat_id negative number but it works fine in case of normal user thread can someone help or fix this issue, please.

**Comment by alexander-akhmetov** [comment]
Hi,

`chat_id` in Telegram can be negative, did you try to receive information about the channel by its id, does it work?
Also, do you receive `sender_id = 0` only when a message in a channel is not signed by an author or always?

**Comment by osamajameelahmad** [comment]
Yes, it was a misunderstanding. I got it Thanks
