### ISSUE TITLE
Incompatible with Windows

### ISSUE THREAD

**Issue by NotoriousPyro** [alexander-akhmetov/python-telegram#364]
Removing `SIGQUIT` and replacing with `SIGTERM` fixes the issue and works on both Linux and Windows:
From:
```python
    def idle(
        self,
        stop_signals: Tuple = (
            signal.SIGINT,
            signal.SIGTERM,
            signal.SIGABRT,
            signal.SIGQUIT,
        ),
```
To:
```python
    def idle(
        self,
        stop_signals: Tuple = (
            signal.SIGINT,
            signal.SIGTERM,
            signal.SIGABRT,
            signal.SIGTERM,
        ),
```

SIGQUIT is Linux specific and should only occur if requesting a core dump, e.g. when pressing `CTRL + \` https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html#index-SIGQUIT

**Comment by alexander-akhmetov** [comment]
Hi. Thanks, makes sense I'll take a look! There are a couple of other places where the library is unix-specific, but it shouldn't be difficult to change.

**Comment by alexander-akhmetov** [comment]
Fixed the signals.
