### ISSUE TITLE
change channel username using link order active usernames? 

### ISSUE THREAD

**Issue by hidufer** [alexander-akhmetov/python-telegram#367]
How I can change my channel uesrname using link order ( usernames that I bought from fragment ) using python-telegram?

![image](https://user-images.githubusercontent.com/17193620/228915936-65a22b43-fd62-45d7-95e9-387a03c0ea82.png)

**Comment by alexander-akhmetov** [comment]
Hi! Please, check the [tdlib documentation](https://core.telegram.org/tdlib/docs/) and [tdlib issues](https://github.com/tdlib/td) for more info on their APIs. `python-telegram` only provides a but more convenient way to call tdlib.
