### ISSUE TITLE
libtdjson.so is doing allot of issues on Cent OS 7

### ISSUE THREAD

**Issue by osamajameelahmad** [alexander-akhmetov/python-telegram#37]
I am facing a lot of issues regarding libtdjson.so in cent os 7. 
OSError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /home/martyn/github/ultima-code/main/scrapers/telegram/telegram_bot_barksdale/telegram/lib/linux/libtdjson.so)

This is one of the issues. can you please help me to?

**Comment by alexander-akhmetov** [comment]
Hi,

It's better to compile libtdjson.so from source code, you can find instructions here: https://tdlib.github.io/td/build.html?language=Python

And then you can specify path to the libtdjson.so: `Telegram(library_path='<path>', ...)`
