### ISSUE TITLE
Failed to connect when trying to deploy on pythonanywhere

### ISSUE THREAD

**Issue by ahmedfamhy3** [alexander-akhmetov/python-telegram#374]
[ 2][t 4][1682851631.149020433][AuthDataShared.cpp:107][#3][!Td]        DcId{1} [auth_key_id:0][state:Empty][created_at:0.000000]
[ 2][t 4][1682851631.149339199][Session.cpp:242][#3][!SessionProxy:1:main]      Generate new session_id 13293172525124092186 for auth key 0 for main DC1
[ 2][t 2][1682851631.149647951][Session.cpp:1439][#3][!Session:1:main::HandshakeActor]  Failed to open connection: [PosixError : Connection refused : 111 : Error on [fd:32] : [149.154.175.50:443] to DcId{1} from [10.0.0.213:47216]]
[ 2][t 4][1682851632.985047817][ConnectionCreator.cpp:913][#3][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:443] to DcId{1}: [PosixError : Network is unreachable : 101 : Failed to connect to [[2001:b28:f23d:f001::a]:443]]
[ 2][t 4][1682851634.985564708][ConnectionCreator.cpp:913][#3][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:80] to DcId{1}: [PosixError : Network is unreachable : 101 : Failed to connect to [[2001:b28:f23d:f001::a]:80]]
[ 2][t 4][1682851638.985537290][ConnectionCreator.cpp:913][#3][!ConnectionCreator]      [[2001:b28:f23d:f001::a]:5222] to DcId{1}: [PosixError : Network is unreachable : 101 : Failed to connect to [[2001:b28:f23d:f001::a]:5222]]

i can't even use proxy https://mtproto.co/ as this proxy uses secret which isn't supported in the library

**Comment by alexander-akhmetov** [comment]
Hi, looking at the issue it can't connect to the servers, it might be something related to pythonanywhere. I never worked with it, so I'm afraid I can't help.
