### ISSUE TITLE
Telegram.login() dont use stdin/stdout

### ISSUE THREAD

**Issue by christofsteel** [alexander-akhmetov/python-telegram#38]
Hi,
I am trying to build a telegram-client with this library, that does not get its inputs from stdin. Unfortunately `Telegram.login()` asks the confirmation code from the standard input. Is it possible to relay the code in any other matter? 
Like one call to start the process of obtaining the code, and a call to another function to verify it. This way it would allow me to forward the request to the UI. 
Another thing I noticed is that by using the library I have a lot of output in my stdout. This seems to be some kind of debug mode. Is it possible to run it outside of a debug mode?

**Comment by alexander-akhmetov** [comment]
Hi,

> Unfortunately Telegram.login() asks the confirmation code from the standard input. Is it possible to relay the code in any other matter?

No, right now [it uses](https://github.com/alexander-akhmetov/python-telegram/blob/master/telegram/client.py#L453) `input()` to read the code. It would be great to have different methods to pass a code though.

> Another thing I noticed is that by using the library I have a lot of output in my stdout. This seems to be some kind of debug mode. Is it possible to run it outside of a debug mode?

`Telegram` class [accepts](https://github.com/alexander-akhmetov/python-telegram/blob/master/telegram/client.py#L44) `tdlib_verbosity` parameter, you can use it to control the output. Sorry that it's not documented.

**Comment by joshms123** [comment]
Following up on this. This would be useful.

**Comment by LeonardoRick** [comment]
Following up to, it will help me a lot. Any update guys?

**Comment by alexander-akhmetov** [comment]
Hi, no, sorry, there is [a branch](https://github.com/alexander-akhmetov/python-telegram/tree/non-blocking-login) with @melfnt changes, I'll try to merge it soon

**Comment by alexander-akhmetov** [comment]
Released in [0.13.0](https://python-telegram.readthedocs.io/en/0.13.0/changelog.html)
