### ISSUE TITLE
Add `py.typed` file

### ISSUE THREAD

**Issue by elricbk** [alexander-akhmetov/python-telegram#394]
`mypy` doesn't want to use type annotations in the package unless `py.typed` file is provided. See [PEP-561][1]. It is easy to fix this for the locally installed package – just `touch py.typed` in the package folder, but it would be better if this file is shipped alongside the package as typehints are already present inline.

[1]: https://peps.python.org/pep-0561/

**Comment by alexander-akhmetov** [comment]
https://github.com/alexander-akhmetov/python-telegram/pull/457
