### ISSUE TITLE
How to create a new conversation ?

### ISSUE THREAD

**Issue by RageshAntonyHM** [alexander-akhmetov/python-telegram#401]
I able to send messages to existing conversation using chat_id, by following the given examples.

But how to send a first new message to number and begin the conversation ?

Also, 

how to call the methods here https://core.telegram.org/methods and process the result

Like this 'className.method' and how to process result?

```
tg = Telegram(...)
params = {'hash': 1}
tg.call_method('contacts.getContactIDs', params = params)
```

**Comment by alexander-akhmetov** [comment]
Hi! Please, check the [tdlib documentation](https://core.telegram.org/tdlib/docs/) and [tdlib issues](https://github.com/tdlib/td) for more info on their APIs.
