### ISSUE TITLE
use parse_mode(MarkdownV2) in send_message

### ISSUE THREAD

**Issue by asarubbo** [alexander-akhmetov/python-telegram#414]
Hello,

I was trying to use `parse_mode` of [sendMessage](https://core.telegram.org/bots/api#sendmessage). I noticed that there are no ways (but please correct me if I'm wrong) via [send_message](https://github.com/alexander-akhmetov/python-telegram/blob/f23565f2ed2516107e6727f02e3dbabe2fba4bb6/telegram/client.py#L228).

Is there a chance to support it or have a working example via `call_method` ?

Thanks

**Comment by shironoY6** [comment]
data = {
            '@type': 'sendMessage',
            'chat_id': chat_id,
            'input_message_content': {
                '@type': 'inputMessageText',
                'text': {
                    '@type': 'formattedText',
                    'text': updated_text,
                    'entities': entities,
                },
            },
        }

        return self._send_data(data)

If you look at the source code for `send_message`, it's just using `_send_data` with the payload `data`.
You can try to craft your payload for MarkdownV2 in this `data`.

https://github.com/alexander-akhmetov/python-telegram/blob/f23565f2ed2516107e6727f02e3dbabe2fba4bb6/telegram/client.py#L216

You could try something like `textParseModeMarkdownV2`?
