### ISSUE TITLE
Not able to send message on Telegram channel

### ISSUE THREAD

**Issue by Patel230** [alexander-akhmetov/python-telegram#421]
{
  "ok": false,
  "error_code": 400,
  "description": "Bad Request: not enough rights to send text messages to the chat"
}

I have added a bot to the channel with all admin access.

Please resolve this issue.

**Comment by AYMENJD** [comment]
This is a known bug with Bot API. It will be fixed soon. It's not related to `python-telegram`.

**Comment by Patel230** [comment]
Lasy 7 days I'm able to post it on the telegram channel. But today suddenly got error 400.
