### ISSUE TITLE
Where I can find last supported tdlib version

### ISSUE THREAD

**Issue by selankon** [alexander-akhmetov/python-telegram#423]
After compiling last (`1.8.20`) it doesn't send messages, is there a place where I can find the last supported version to compile it by my own? 

Thx

**Comment by selankon** [comment]
Mmm now is sending the messages properly... idk why this happened. btw, where i can find the info i ask above?

**Comment by shironoY6** [comment]
Added support for tdlib > 1.8.5. (thanks to @JleMyP)

According to 

https://python-telegram.readthedocs.io/en/latest/changelog.html

**Comment by selankon** [comment]
Thanks!
