### ISSUE TITLE
Does this client include `delete_file` functionality?

### ISSUE THREAD

**Issue by adithyaamara** [alexander-akhmetov/python-telegram#433]
I am currently using `python-telegram-bot` for a custom application based on telegram. What it is missing is, there is no `delete_file` functionality. I went through TDLib docs to find a way to delete file and found this: https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1delete_file.html. I just hope this client can help me delete a file by file id.

> PS: I know we can use delete_message, But files are still accessible via file_id for some extended amount of time.

**Comment by alexander-akhmetov** [comment]
Hi, you can use `call_method` to call anything in tdlib. For example:

```python
tg.call_method('getUser',  params={'user_id': user_id})
```
