### ISSUE TITLE
issues with version 

### ISSUE THREAD

**Issue by abdullaevich700** [alexander-akhmetov/python-telegram#439]
$ python get_me.py 
Traceback (most recent call last):
  File "C:\programming\telegram-bots\python-telegram\examples\get_me.py", line 4, in <module>
    from telegram.client import Telegram
  File "C:\programming\telegram-bots\python-telegram\venv\Lib\site-packages\telegram\client.py", line 27, in <module>
    from telegram import VERSION
ImportError: cannot import name 'VERSION' from 'telegram' (C:\programming\telegram-bots\python-telegram\venv\Lib\site-packages\telegram\__init__.py)

meanwhile 

$ pip show python-telegram
Name: python-telegram
Version: 0.18.0
Summary: Python library to help you build your own Telegram clients
Home-page: https://github.com/alexander-akhmetov/python-telegram
Author: Alexander Akhmetov
Author-email: me@aleks.sh
License:
Location: C:\programming\telegram-bots\python-telegram\venv\Lib\site-packages
Requires: telegram-text
Required-by:

**Comment by alexander-akhmetov** [comment]
It might be related to this issue: https://github.com/alexander-akhmetov/python-telegram/issues/207

Can you please check if it's still the case if you use virtualenv?
