### ISSUE TITLE
AttributeError: module 'signal' has no attribute 'SIGQUIT'

### ISSUE THREAD

**Issue by mhamri** [alexander-akhmetov/python-telegram#448]
I'm opening #264 as look like the issue still persist. I saw that previous issue closed as completed but no PR or commit is referenced 

can't use the library on windows

```sh
> python --version
Python 3.12.2
```
python-telegram==0.18.0

**Comment by alexander-akhmetov** [comment]
Hi! Yes, the library does not support Windows.

**Comment by shotnothing** [comment]
Hi! Wasn't a fix for this proposed in #364 and pushed in #408 ?
