### ISSUE TITLE
Asyncio?

### ISSUE THREAD

**Issue by dausruddin** [alexander-akhmetov/python-telegram#45]
Hi. In tdlib repo, it is mentioned that "The wrapper uses the full power of asyncio" . But is it true?

**Comment by alexander-akhmetov** [comment]
Hi. No, the library doesn't use `asyncio`, but it is not blocking by default. 

All calls to a `Telegram` instance return `AsyncResult` instances, which have a blocking method `wait` to get the results.

**Comment by melfnt** [comment]
Isn't [the current `wait` implementation](https://github.com/alexander-akhmetov/python-telegram/blob/master/telegram/utils.py#L32) a busy waiting? It seems so to me.
Maybe we can change this behavior using a semaphore or something like that to awake the `AsyncResult` object when the the result is ready?

**Comment by alexander-akhmetov** [comment]
Yes, it is. It's not necessary to call it though, when the telegram client has an update, it puts the data to the AsyncResult instance. 

> Maybe we can change this behavior using a semaphore or something like that to awake the AsyncResult object when the the result is ready?

I'm not sure what exactly it gives us, could you explain it more, please?

**Comment by melfnt** [comment]
> Yes, it is. It's not necessary to call it though, when the telegram client has an update, it puts the data to the AsyncResult instance. `wait` method just sleeps until the data is there.
> 
> > Maybe we can change this behavior using a semaphore or something like that to awake the AsyncResult object when the the result is ready?
> 
> I'm not sure what exactly it gives us, could you explain it more, please?

It saves us from a busy waiting, isn't it enough?

**Comment by alexander-akhmetov** [comment]
> Maybe we can change this behavior using a semaphore or something like that to awake the AsyncResult object when the the result is ready?

Oh, you were talking about busy waiting, I got it wrong. Yes, it would be better to replace it :)
