### ISSUE TITLE
topics

### ISSUE THREAD

**Issue by yemix** [alexander-akhmetov/python-telegram#454]
Hey, is there a way to send a message to a specific topic in a group?

**Comment by yemix** [comment]
I trief to change the client.py to support "message_thread_id" from the official tdlib docu but it dont work. Can u look into it?
If not, the bot only send messages to "General".

**Comment by alexander-akhmetov** [comment]
Hi, try to use the more generic [call_method](https://github.com/alexander-akhmetov/python-telegram/blob/b1ee51c89de7e73a0c894f6dbebb7197153e6b2a/telegram/client.py#L500), it accepts a dictionary with the data for the call to tdjson. [For example](https://github.com/alexander-akhmetov/python-telegram/blob/b1ee51c89de7e73a0c894f6dbebb7197153e6b2a/telegram/client.py#L354).

You can also increase the logging level in tdjson to debug:

```python
tg = Telegram(
    ...,
    tdlib_verbosity=7,
)
```
