### ISSUE TITLE
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by batreller** [alexander-akhmetov/python-telegram#456]
Hello, 

I am facing that issue on fedora 39
I have googled that issue many times and what everyone says is I just need to install openssl, well I did it but still nothing works, nothing changed after I did

```
sudo dnf install openssl-devel
sudo dnf install openssl
```

```
liveuser@localhost-live:~/Desktop/temp1$ uname -r
6.5.6-300.fc39.x86_64
liveuser@localhost-live:~/Desktop/temp$ python --version
Python 3.12.0
```
![image](https://github.com/alexander-akhmetov/python-telegram/assets/120225698/eae276e8-ff02-4671-ad4a-f9cba49ea060)

```
liveuser@localhost-live:~/Desktop/temp$ sudo python temp.py
Traceback (most recent call last):
  File "/home/liveuser/Desktop/temp/temp.py", line 4, in <module>
    tg = Telegram(
         ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telegram/client.py", line 147, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telegram/tdjson.py", line 33, in __init__
    self._build_client(library_path, verbosity)
  File "/usr/local/lib/python3.12/site-packages/telegram/tdjson.py", line 40, in _build_client
    self._tdjson = CDLL(library_path)
                   ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

I have also tried using ubuntu, I installed openssl as well

```
sudo apt install openssl
sudo apt install libssl-dev
```
but still facing same issue
```
root@hackatroncar:~# sudo python3 temp.py
Traceback (most recent call last):
  File "/root/temp.py", line 4, in <module>
    tg = Telegram(
  File "/usr/local/lib/python3.10/dist-packages/telegram/client.py", line 147, i           n __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/usr/local/lib/python3.10/dist-packages/telegram/tdjson.py", line 33, in            __init__
    self._build_client(library_path, verbosity)
  File "/usr/local/lib/python3.10/dist-packages/telegram/tdjson.py", line 40, in            _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
```
![image](https://github.com/alexander-akhmetov/python-telegram/assets/120225698/71907908-2bda-4eaf-91bb-c3923780942a)

here is info about my python and ubuntu versions
```
root@hackatroncar:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
root@hackatroncar:~# python3 --version
Python 3.10.12
```

**thanks in advance**

**Comment by alexander-akhmetov** [comment]
Hi! Yes, unfortunately the compiled tdlib file that goes with the library is built with a dynamically linked, specific version of openssl. Currently, the solution would be to ether [build tdlib yourself](https://tdlib.github.io/td/build.html) and then specify the path to the `libtdjson.so`:

```python
Telegram(
    library_path='/path/to/libtdjson.so',
    ...
)
``` 

Or you can use the [Docker image](https://github.com/alexander-akhmetov/python-telegram?tab=readme-ov-file#docker) to run your program.

**Comment by batreller** [comment]
Thanks, it did work, how can I read files where session is stored now? I am talking about these files:
td.binlog
db.sqlite
db.sqlite-shm
db.sqlite-wal

**Comment by alexander-akhmetov** [comment]
You can [set files_directory](https://github.com/alexander-akhmetov/python-telegram/blob/a8b59baa73d2e87948a67bec9a818f731c551dd8/telegram/client.py#L68) when you initialize `Telegram`. By default it uses just a [temporary folder](https://github.com/alexander-akhmetov/python-telegram/blob/a8b59baa73d2e87948a67bec9a818f731c551dd8/telegram/client.py#L131). Most likely it will be in `/tmp/.tdlib_files` or something like that. I think `tdlib` also logs the paths sometimes.

**Comment by batreller** [comment]
but how to read them? they are encrypted, aren't they? how do I decrypt them manually so I can read them?

**Comment by alexander-akhmetov** [comment]
They are encrypted by tdlib, I don't know how to read them. It's better to check [tdlib](https://github.com/tdlib/td) documentation or issues.

**Comment by batreller** [comment]
Do you know where from these orange logs are?

![image](https://github.com/alexander-akhmetov/python-telegram/assets/120225698/42b892fe-18fb-488b-88d1-27bc13b55695)
