### ISSUE TITLE
Outdated tdlib

### ISSUE THREAD

**Issue by MalteToenjes** [alexander-akhmetov/python-telegram#46]
Hey since the tdlib library in the project is outdated, I would like compile the newest (1.5) version. But I don't know how, since there are several options...Could you tell me the command how you compiled the lib?

**Comment by alexander-akhmetov** [comment]
Hi!

I have a repository with compiled tdlib: https://github.com/alexander-akhmetov/tdlib-compiled
It lacks a good description, I'll add some instruction later, but there are two dockerfiles with commands.

**Comment by melkor217** [comment]
Does that mean you could just update tdlib.so to start using all new cool stuff (via Telegram._send_data or something)?

**Comment by alexander-akhmetov** [comment]
> Does that mean you could just update tdlib.so to start using all new cool stuff (via Telegram.call_method or something)?

Yes. 

I just updated the tdlib: https://github.com/alexander-akhmetov/tdlib-compiled, there is one issue though, for linux there is only a `libc` version for now, compilation with `musl` [isn't working](https://github.com/tdlib/td/pull/716) right now.
