### ISSUE TITLE
get_chats() returns empty chat list

### ISSUE THREAD

**Issue by rs-development** [alexander-akhmetov/python-telegram#58]
I can run the ping pong example but i can not receive chat ids.

	from telegram.client import Telegram

	tg = Telegram(
	    api_id='0123455',
	    api_hash='blablabla',
	    phone='00491766822222',  # you can pass 'bot_token' instead
	    database_encryption_key='changekey123',
	)
	tg.login()

	    # if this is the first run, library needs to preload all chats
	    # otherwise the message will not be sent
	result = tg.get_chats()
	result.wait()
	print(result.update)

This is the result:

    {'@type': 'chats', 'chat_ids': [], '@extra': {'request_id': 'd8acbe24880e4385a8a7ce8b79a2bbda'}}

Any idea how to solve this?

**Comment by melkor217** [comment]
Short answer: you should pass arguments to get_chats.

Here is an example:

```
    def get_chats(offset_order=2 ** 63 - 1, offset_chat_id=0):

        def pairwise(iterable):
            a = iter(iterable)
            return zip(a, a)

        chats = tg.get_chats(
            offset_order=offset_order, offset_chat_id=offset_chat_id
        )
        chats.wait()
        chat_list = chats.update["chat_ids"]
        if len(chat_list) < 1:
            return []

        last_chat = tg.get_chat(chat_list[-1])
        last_chat.wait()
        return chat_list + get_chats(
            offset_order=int(last_chat.update["order"]), offset_chat_id=chat_list[-1]
        )
```

Where `tg` is Telegram object. Be careful, there is no proper error handling in my example!

You can just use `offset_order=2 ** 63 - 1, offset_chat_id=0` to get first page.

**Comment by knine3** [comment]
This works for me:

```
tg.get_chats(offset_order=9223372036854775807)  #9223372036854775807 is the max value of offset order
```

**Comment by melkor217** [comment]
> This works for me:
> 
> ```
> tg.get_chats(offset_order=9223372036854775807)  #9223372036854775807 is the max value of offset order
> ```

I guess that's an equivalent of `tg.get_chats(offset_order=2 ** 63 - 1, offset_chat_id=0)`.

It will only return first page. Page size is determined by server side (it is usually 100 for me).

https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_chats.html

**Comment by LeonardoRick** [comment]
@melkor217 what do you mean when you say "first page"?

**Comment by melkor217** [comment]
> @melkor217 what do you mean when you say "first page"?

You can't get all chats at once, you have to iterate over offset_order and offset_chat_id starting with something like `offset_order=2 ** 63 - 1, offset_chat_id=0`
