### ISSUE TITLE
Client wait for result forever  if result update have only @type='ok'

### ISSUE THREAD

**Issue by slenz** [alexander-akhmetov/python-telegram#67]
Hello,

I play with master branch of python-telegram and found a bug. When I try to set  my first/last name then AsyncResult wait forever. It happens because Event self._ready.set() in the AsyncResult is set only if update `@type != 'ok'`.
I guess it was made for login purposes where result `@type='ok' `is not means that result is ready.

This is my code:
```...
   tg.login()

    result = tg.get_me()
    result.wait()
    print(result.update)

    logger.debug("Setting name")
    result = tg.call_method('setName', params={'first_name': 'First', 'last_name': 'Last'})
    result.wait() # there it waits forever
    print(result.update)
```

I changed the  `parse_update` method of AsyncResult as follows by adding condition `if self.id != 'updateAuthorizationState'` and it start working. 
```
    def parse_update(self, update: Dict[Any, Any]) -> None:
        if update.get('@type') == 'ok':
            self.ok_received = True
            # added following 3 lines
            if self.id != 'updateAuthorizationState':
                self._ready.set()
                return True
            return False

        if update.get('@type') == 'error':
            self.error = True
            self.error_info = update
        else:
            self.update = update

        self._ready.set()

        return True
```
But I not 100% sure that my way is correct, I just started to play with Telegram lib a day ago..

**Comment by alexander-akhmetov** [comment]
Should be fixed in #76 and #77, thanks @slenz and @h4x3rotab
