### ISSUE TITLE
[FeatureRequest] Add getUserFullInfo() support

### ISSUE THREAD

**Issue by AIshutin** [alexander-akhmetov/python-telegram#71]
In the TDLIB update event, there is only the 'sender_user_id' field and no other user identification. Currently, there is no way to get first and last names using python-telegram.
As far as I know, to get that information the client should use getUserFullInfo() method. Please, add it.

**Comment by alexander-akhmetov** [comment]
Hi, thanks for the report, will add the method.

While it's not implemented you can use `call_method` to call any method:

```
tg.call_method('getUserFullInfo', params={...})
```

**Comment by AIshutin** [comment]
Thank you very match!

**Comment by ByPort** [comment]
Hello @alexander-akhmetov , I would like to contribute to a project. Is this issue actual? Can I open a PR for it?

**Comment by alexander-akhmetov** [comment]
@ByPort Hi, sure, feel free to open a PR
