### ISSUE TITLE
Use specific openssl ver

### ISSUE THREAD

**Issue by own2pwn** [alexander-akhmetov/python-telegram#75]
is it possible to provide my own version of openssl? i've installed via pip3 and it seems that `libtdjson` requires right only `libssl.1.0.0`, while there's `libssl.1.1` available on my system

**Comment by alexander-akhmetov** [comment]
No, right now it's not possible. But you can [build](https://tdlib.github.io/td/build.html?language=Python) your own version of tdlib and use it with python-telegram:

```
tg = Telegram(
    ...
    library_path='/path/to/libtdjson.so',
)
```
