### ISSUE TITLE
[Question] How to change autodownload settings / download remote files?

### ISSUE THREAD

**Issue by AIshutin** [alexander-akhmetov/python-telegram#78]
Hi!
Thanks for this awesome project! Can you please explain to me how to change auto download settings or to download any file manually? Also, can I manually delete downloaded file using 
`rm $some_tg_downloaded_file`?

Again big thanks,
Andrew Ishutin

P. S. Should I open this issue in the TDLib repo?

**Comment by AIshutin** [comment]
I've found https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1delete_file.html
But after some trials, I still cannot understand how to get local file path:
downloadFile and then getFile give me None

**Comment by alexander-akhmetov** [comment]
Hi! `downloadFile` adds file to the downloading queue. Then you have to listen for updates with` @type: updateFile` and when the file is downloaded you will receive an update with information about the local file:

```python
def file_handler(update):
    local_file = update.get('file', {})('local', {})
    is_downloading_completed = local_file.get('is_downloading_completed')
    
    if is_downloading_completed:
        local_path = local_file['path']
        ...

tg.add_update_handler('updateFile', file_handler)

file_id = ...
tg.call_method('downloadFile', params={'file_id': file_id, 'priority': 1})
```


> Can you please explain to me how to change auto download settings

I think, you can change auto download settings using methods `getAutoDownloadSettingsPresets ` and `setAutoDownloadSettings` with tdlib >= 1.5.0.

**Comment by AIshutin** [comment]
It works. You saved my life.

**Comment by alexander-akhmetov** [comment]
Happy to help :)

**Comment by drzraf** [comment]
I don't get it.
Looking at the `file_handler`: `update.get('file', {})`  returns a dict (not a callable)

**Comment by alexander-akhmetov** [comment]
Hi! It’s probably a typo and should be `update.get('file', {}).get('local', {})`

**Comment by drzraf** [comment]
And how is the local path determined? Automatically?

I've set `files_directory` (and the db and `files/` are there), but while the result of `getRemoteFile` correctly return an (integer) ID, it also returns `expected_size = 0` and `localFile`'s `path=""`).

When passing such an ID to `dowloadFile`, it fails. Should I look for the error at the `getFile` setup or the `downloadFile` one (or the init)?

**Comment by AlcoholicCoder** [comment]
@alexander-akhmetov The `updateFile` handler is not getting triggered. Please help.
Code prints `Downloading file with file_id: XXX` and it must be calling `downloadFile` method but after that there are no updates in `file_handler` method.
My code:
```python
# Login to the telegram as a user
tg.login()

# Print dictionary in a readable format
def print_dict(d):
    print(json.dumps(d, sort_keys=True, indent=4))

# Handler for file updates
def file_handler(updateObj):
    print_dict("file_handler", updateObj)
    local_file = updateObj.get('file', {}).get('local', {})
    is_downloading_completed = local_file.get('is_downloading_completed', False)
    
    if is_downloading_completed:
        local_path = local_file.get('path', None)
        print("File downloaded to:", local_path)

# Handler for new messages
def new_message_handler(updateObj):
    # print_dict(updateObj)

    # the message object
    messageObj = updateObj.get('message', None) 
    if messageObj is None:
        print("No message object found")
        return

    # content of the message
    contentObj = messageObj.get('content', None) 
    if contentObj is None:
        print("No content object found")
        return

    # get the type of the content
    content_type = contentObj.get('@type', None)
    if(content_type == 'messageText'):
        message = contentObj.get('text', {}).get('text', None)
    elif(content_type == 'messagePhoto'):
        file_id = contentObj.get('photo', {}).get('sizes', [])[0].get('photo', {}).get('remote', {}).get('id', None)
        print("Downloading file with file_id:", file_id)
        tg.call_method(method_name='downloadFile', params={'file_id': file_id, 'priority': 1})
        message = contentObj.get('caption', {}).get('text', None)
    else:
        message = None
    
    if message is None or message == "":
        print("Message is empty or not found")
        return
    
    chat_id = messageObj.get('chat_id', None)
    message_id = messageObj.get('id', None)
    is_channel_post = messageObj.get('is_channel_post', False)
    date = messageObj.get('date', None)
    print_dict({
        "chat_id": chat_id,
        "message_id": message_id,
        "is_channel": is_channel_post,
        "date": date,
        "message": message
    })
    print("--------------------")

# Add the handler to the telegram client
tg.add_update_handler(handler_type="updateNewMessage", func=new_message_handler)

# Add the handler to handle file updates
tg.add_update_handler(handler_type='updateFile', func=file_handler)

# Listen for updates
tg.idle()
```

**Comment by AlcoholicCoder** [comment]
> @alexander-akhmetov The `updateFile` handler is not getting triggered. Please help. Code prints `Downloading file with file_id: XXX` and it must be calling `downloadFile` method but after that there are no updates in `file_handler` method. My code:
> 
> ```python
> # Login to the telegram as a user
> tg.login()
> 
> # Print dictionary in a readable format
> def print_dict(d):
>     print(json.dumps(d, sort_keys=True, indent=4))
> 
> # Handler for file updates
> def file_handler(updateObj):
>     print_dict("file_handler", updateObj)
>     local_file = updateObj.get('file', {}).get('local', {})
>     is_downloading_completed = local_file.get('is_downloading_completed', False)
>     
>     if is_downloading_completed:
>         local_path = local_file.get('path', None)
>         print("File downloaded to:", local_path)
> 
> # Handler for new messages
> def new_message_handler(updateObj):
>     # print_dict(updateObj)
> 
>     # the message object
>     messageObj = updateObj.get('message', None) 
>     if messageObj is None:
>         print("No message object found")
>         return
> 
>     # content of the message
>     contentObj = messageObj.get('content', None) 
>     if contentObj is None:
>         print("No content object found")
>         return
> 
>     # get the type of the content
>     content_type = contentObj.get('@type', None)
>     if(content_type == 'messageText'):
>         message = contentObj.get('text', {}).get('text', None)
>     elif(content_type == 'messagePhoto'):
>         file_id = contentObj.get('photo', {}).get('sizes', [])[0].get('photo', {}).get('remote', {}).get('id', None)
>         print("Downloading file with file_id:", file_id)
>         tg.call_method(method_name='downloadFile', params={'file_id': file_id, 'priority': 1})
>         message = contentObj.get('caption', {}).get('text', None)
>     else:
>         message = None
>     
>     if message is None or message == "":
>         print("Message is empty or not found")
>         return
>     
>     chat_id = messageObj.get('chat_id', None)
>     message_id = messageObj.get('id', None)
>     is_channel_post = messageObj.get('is_channel_post', False)
>     date = messageObj.get('date', None)
>     print_dict({
>         "chat_id": chat_id,
>         "message_id": message_id,
>         "is_channel": is_channel_post,
>         "date": date,
>         "message": message
>     })
>     print("--------------------")
> 
> # Add the handler to the telegram client
> tg.add_update_handler(handler_type="updateNewMessage", func=new_message_handler)
> 
> # Add the handler to handle file updates
> tg.add_update_handler(handler_type='updateFile', func=file_handler)
> 
> # Listen for updates
> tg.idle()
> ```

My bad id requires this id:
`file_id = contentObj.get('photo', {}).get('sizes', [])[-1].get('photo', {}).get('id', None)`

**Comment by bugbaal** [comment]
I tried to use the same method in the example, but file_handler(...) is never called.
I tried to use "id" and "unique_id" too, but nothing.

What could be the problem?

```
           "remote": {
              "@type": "remoteFile",
              "id": "AgACAgQAAxUAAWetKv*****",
              "unique_id": "AQAD9cYx*****",
              "is_uploading_active": false,
              "is_uploading_completed": true,
              "uploaded_size": 61758
            }
```
