### ISSUE TITLE
How to create a new group?

### ISSUE THREAD

**Issue by VenkatTeja** [alexander-akhmetov/python-telegram#82]
Couldn't find how to create a new group programmatically in the documentation. Kindly help me with it.

**Comment by alexander-akhmetov** [comment]
Hi,
It depends on the chat type, `tdlib` provides a few methods: [createPrivateChat](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1create_private_chat.html), [createNewBasicGroupChat](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1create_new_basic_group_chat.html), [createNewSupergroupChat](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1create_new_supergroup_chat.html#a616d1ec015cd3ea1d47ad93ef998489d). You can find them [here](https://core.telegram.org/tdlib/docs/functions_func_c.html#index_c) in the list.

To call any method use `Telegram.call_method`:

```python
tg = Telegram(...)
tg.call_methog('createNewSupergroupChat', params={...})
```
