### ISSUE TITLE
I'm getting system error in Windows 10 

### ISSUE THREAD

**Issue by RomanSafe** [alexander-akhmetov/python-telegram#84]
Hello!
I used python-telegram library to build Telegram client. When I had launched python script in PowerShell I got pop-up window with error message. Unfortunately I didn't make a screenshot. The message said that I'm trying to launch file dedicated for another operating system and showed the path to the file contained "linux" directory.

**Comment by alexander-akhmetov** [comment]
Hi,
Yes, python-telegram doesn't have tdlib for windows, you have to [build it](https://tdlib.github.io/td/build.html) yourself and pass the path to the client:

```python
tg = Telegram(
    ...
    library_path='/path/to/library/file',
)
```

**Comment by RomanSafe** [comment]
Thank you very much for the response!
