### ISSUE TITLE
Is there function that I can get someone's Current Status (Online or Offline)?

### ISSUE THREAD

**Issue by ahmed-gelemli** [alexander-akhmetov/python-telegram#96]
Hello, if someone knows answer to that please answer.
Thanks!

**Comment by alexander-akhmetov** [comment]
Hi,

I think, you need [getUser](https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_user.html) method (`Telegram.get_user`).

https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1get_user.html
https://core.telegram.org/tdlib/docs/classtd_1_1td__api_1_1user.html
